### ISSUE TITLE
Featuere-Requst

### ISSUE THREAD

**Issue by KGBist2000** [antedebaas/DMARC-Reports#106]
When from one reported domain more then one record availible and one is red and the other green, the sum status on the dashboard could be orange instead of red, see screen2 (to indicated diffrent results,)

![screen1](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/81825812/7c5d44a4-8b26-4f87-a3fb-988636c56bc7)
![screen2](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/81825812/474493c7-96c7-47bf-9247-903b25fede26)

**Comment by antedebaas** [comment]
personally i wouldn't, i already use yellow/orange for some statuses that are warnings.
becides, a failure should never be presented as non fatal.
