### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'users' doesn't exist

### ISSUE THREAD

**Issue by mshannaq** [antedebaas/DMARC-Reports#107]
### SQLSTATE[42S02] Base table or view not found: 1146 Table 'users'

**Describe the bug**
After installing and running `bash update.sh` and `installservice.sh` and goto http://hostname.dev/ it forward me to http://hostname.dev/setup and I entered the values then I see that `.env.local` created. but then error message "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dmarcdb.users' doesn't exist" appear in web browser.

**Are you using the Docker image?**
- [ ] Yes
- [x] No

**Database used**
- [x] MySQL/MariaDB
- [ ] PostgreSQL
- [ ] SQLite

**Error Messages**
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'users' doesn't exist

**Steps to Reproduce**
Please provide detailed steps to reproduce the problem:
1. install
2. goto http://hostname.dev/setup and enter the values

**Screenshots**
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/162535/f1761d58-ba6e-49d1-89ca-dc1c86ea0b57)

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04
 - Control panel: CloudPanel , site created as symfony 7 env.
 - Browser  Chrome
 - Version [e.g. 24.04]

**Comment by mshannaq** [comment]
I noticed that as @k04d01 said in https://github.com/antedebaas/DMARC-SMTPTLS-Reports/issues/104

after i have startet /setup in my webbrowser and see the error then  run `bash update.sh` again in console. 

I can see databases tables created.

then I return to http://hostname.dev/setup and continue creating the user.

do I think  `bash update.sh`  step must be after the http://hostname.dev/setup in instructions.

**Comment by antedebaas** [comment]
thank you for reporting.
there was a bug in the setup script preventing the normal setup flow.
this is fixed in 1.14.1.

Please let me know if this solves the issue for you.

**Comment by antedebaas** [comment]
cloing this as it should be fixed.
if not please reopen
