### ISSUE TITLE
duplicate report when parsing from email

### ISSUE THREAD

**Issue by mshannaq** [antedebaas/DMARC-Reports#108]
### Issue Template

**Describe the bug**
Today I see the application duplicate the report for the same report  , while it is just 1 email in the IMAP email.
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/162535/18a858fa-5bfd-4a08-b844-ac96f689983f)

while in on email just 1 email
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/162535/8b380c9b-258b-41c1-a620-f27e91f0c451)

Iam using [v1.14.0](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/releases/tag/v1.14.0)

do you think the problem because I set up the application to keep and parsed messages in the IMAP Email. and I must select to delete it after parse?

**Are you using the Docker image?**
- [ ] Yes
- [x] No

**Database used**
- [x] MySQL/MariaDB
- [ ] PostgreSQL
- [ ] SQLite

**Environment (please complete the following information):**
 - OS: Linux
 - Browser

**Comment by antedebaas** [comment]
> do you think the problem because I set up the application to keep and parsed messages in the IMAP Email. and I must select to delete it after parse?
No, i keep the messages as well and never had this problem.

what does the logs page say for that time?
have there been multiple runs of the getfrommailbox process for example?

**Comment by mshannaq** [comment]
there is no reference for log to know which report it parse

I can see the Log as 
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/162535/bb6abeeb-8197-410a-921a-77c633088410)

but I cannot detrmine Log to know that log for which report is related to.

**Comment by antedebaas** [comment]
Note to self: add lock state

**Comment by antedebaas** [comment]
I added a lock to the mail process in v1.15.0 and improved logging.
This should fix it.
if not feel free to reopen this issue
