### ISSUE TITLE
GetReportsFromMailbox command was already running.

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#113]
**Describe the bug**
Error message in logs since latest update

**Are you using the Docker image?**
- [ X] Yes
- [ ] No

**Database used**
- [ X] MySQL/MariaDB
- [ ] PostgreSQL
- [ ] SQLite

**Error Messages**
GetReportsFromMailbox command was already running.

**Expected behavior**
Normal email fetch schedule

**Screenshots**
![Screenshot 2024-06-20 151744](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/4bfb7d1b-a730-4fd2-895f-decc354074f8)

**Environment (please complete the following information):**
 - latest Debian 12
 - Vivaldi (Chrome)
 - 6.8.3381.44

**Additional context**
This error appears since the latest update from yesterday

**Comment by antedebaas** [comment]
This can happen when either one of 2 cases occur:
- the checkmail command is already running and holds a lock for the second invocation. This is normal behavior as it prevents duplicate processes. 
- the checkmail command crashed in an earlier attempt not releasing the lock. In this case please check the systems logs. You can release the lock with the `php .\bin\console app:removemaillock ` command

**Comment by antedebaas** [comment]
In case of the latter please let me know what crashed it

**Comment by bundyland** [comment]
Ante,

thanks for your feedback.

If I try `docker exec -t dmarc-smtptls-reports-web-1 php .\bin\console app:removemaillock` I just get `Could not open input file: .binconsole`.

Could you please help me with the correct command?

Thank you!

**Comment by antedebaas** [comment]
php /var/www/html/bin/console app:removemaillock

**Comment by bundyland** [comment]
Thank you.

I've run this command and got:
![Screenshot 2024-06-21 112724](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/e10f243d-53dd-46fe-8668-3d28f644c863)

After `docker compose down && docker compose up -d` I've hit `Check Mailbox now` and got immediately again:

![Screenshot 2024-06-21 112909](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/31878c8f-0d4b-44e5-be6b-aa36229baf63)

For the moment I will roll back to an older version as I never had these problems before the latest release.

Thanks once again for your support.

Cheers...

**Comment by bundyland** [comment]
Update: switched back to version 1.14.2 and problem is gone.

**Comment by antedebaas** [comment]
the problem is probably still there, older versions didnt do a check i added. this could cause other problems instead so i would not recoomend it

**Comment by bundyland** [comment]
Hi Ante,

sorry for the late response.

Here are my docker compose logs: [logs.txt](https://github.com/user-attachments/files/15936574/logs.txt)

I see some warnings in there, but due to a lack of knowledge it doesn't ring a bell to me. Hopefully the logs are helpful for you anyway.

Thanks and best...

**Comment by antedebaas** [comment]
None of the errors are related to the getreportsfrommailbox command.

could you run the following command on 1 line and give me the output.

`php /var/www/html/bin/console app:removemaillock; php /var/www/html/bin/console app:getreportsfrommailbox `

this should run them both in sequence

**Comment by bundyland** [comment]
Sure. I got this:

![Screenshot 2024-06-22 193751](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/08e2b966-1bd7-4fe2-808d-c01596d2996e)

Sorry, my server speaks German. "Kommando nicht gefunden" means "command not found", but I'm sure Dutch people understand German very well. 😉

**Comment by antedebaas** [comment]
Yep can read German :)

try this one:
`docker expect -t smtp-tls-reports-1 php /var/www/html/bin/console app:removemaillock; docker expect -t smtp-tls-reports-1  
php /var/www/html/bin/console app:getreportsfrommailbox  `

**Comment by bundyland** [comment]
This is the result:

![Screenshot 2024-06-22 201926](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/fe42ca07-6d3b-4a08-bcd8-e4d4da32a82d)

**Comment by antedebaas** [comment]
Autocorrect changed stuff;
try this one:
`docker exec -t smtp-tls-reports-1 php /var/www/html/bin/console app:removemaillock; docker exec -t smtp-tls-reports-1  
php /var/www/html/bin/console app:getreportsfrommailbox  `

**Comment by bundyland** [comment]
I've changed your command to the correct container name and got positive results:

![Screenshot 2024-06-22 211606](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/692ead3a-a003-45dd-aaa4-56016bcc5ebb)

But after clicking on `Check mailbox now` the same error message `GetReportsFromMailbox command was already running.`

Strange, isn't it?

**Comment by bundyland** [comment]
It seems to work as long as I don't hit the `check mailbox now` button. If I only let the cron scheduled mail check running, the error message doesn't appear. Hope this helps.

**Comment by antedebaas** [comment]
Yeah that helps a lot actually.
I think I have enough reason now to retire that ugly button 😃

**Comment by bundyland** [comment]
Yeah, time to say goodbye! 😃

**Comment by bundyland** [comment]
Dag Ante,

I'm sorry to tell you, but after a few hours of regular cron fetching mails, the error message appeared suddenly again although I haven't touched the "check mailbox now" button. So for the moment I think I better stay with v.1.14.2 until we have found the real issue.

**Comment by antedebaas** [comment]
If it happens without any other logged errors and it’s only now and then it’s not a problem. In fact it’s preventing duplicate processes so that’s a good thing.

**Comment by antedebaas** [comment]
What is your cron schedule?

**Comment by bundyland** [comment]
> If it happens without any other logged errors and it’s only now and then it’s not a problem. In fact it’s preventing duplicate processes so that’s a good thing.

Unfortunately this is not the case. The error appears at every scheduled mail check (once per hour) and no report is imported.
After I have run your command above, it works for a while, but then it stops at some point. I need to run the command again. Otherwise it gets stuck.

**Comment by antedebaas** [comment]
have you checked the mailbox for flagged messages?
any other errors in the logs around the time the check starts to fail?

**Comment by bundyland** [comment]
No flagged mails and nothing other than what I had already written above. Really strange.

But please don't waste your time. As it seems that I'm the only one with this problem, you can close this case. I'll stay with 1.14.2 as this version is just running fine for me. And perhaps the problem will resolve itself with one of the next releases. 😃

**Comment by antedebaas** [comment]
If rather fix the underlying issue
