### ISSUE TITLE
GetReportsFromMailbox command was already running

### ISSUE THREAD

**Issue by deanfourie1** [antedebaas/DMARC-Reports#124]
### Issue Template

**Describe the bug**

The error just keeps repeating and as a result no reports are being received.

<img width="1214" alt="image" src="https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/71812804/dd2f6f94-de01-477a-aa0b-a21382726739">

**Are you using the Docker image?**
- Yes

**Database used**
- PostgreSQL

**Error Messages**
Please paste any error messages here.

See image above.

**Steps to Reproduce**
Please provide detailed steps to reproduce the problem:

Nothing, just every time it attempts to check the mailbox it fails with this error.

**Expected behavior**

Mails to be checked and received..

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, macOS, Linux]
Debian 12
 - Browser [e.g. Chrome, Firefox]
 Chrome

**Additional context**

**Comment by antedebaas** [comment]
Did you do any container restarts?
And are there any exceptions in the logs at the time this first appeared?
any flagged messages in the mailbox?

You can run the following command to remove the lock.
`php /var/www/html/bin/console app:removemaillock`

**Comment by deanfourie1** [comment]
Thanks, that worked however it has failed again.
There are no flagged messages in the mailbox, however I did find some messages in the "Junk" folder which I moved to the Inbox.

![image](https://github.com/user-attachments/assets/159477cc-739f-4795-8d99-29d236043c7e)

**Comment by antedebaas** [comment]
could you try and see if using antedebaas/dmarc-reports-testing:sha-c4c254b fixes it?
there is no database/migrations in there just some code changes that i hope will work

**Comment by deanfourie1** [comment]
Was going well for a while, and then again :(

![image](https://github.com/user-attachments/assets/c0e6f109-c492-4c23-81e2-133ea5de2198)

**Comment by tobsowo** [comment]
Came here to also post this.
`GetReportsFromMailbox command was already running.`

**Comment by antedebaas** [comment]
> Was going well for a while, and then again :(
> 
> ![image](https://private-user-images.githubusercontent.com/71812804/349280896-c0e6f109-c492-4c23-81e2-133ea5de2198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDY3NDQsIm5iZiI6MTcyMTIwNjQ0NCwicGF0aCI6Ii83MTgxMjgwNC8zNDkyODA4OTYtYzBlNmYxMDktYzQ5Mi00YzIzLTgxZTItMTMzZWE1ZGUyMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4NTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYmNjYmIyNTIyYTVkZTQ5ZDJlY2IyNzQ2ODEzZDNkOGE1MzdlOWFlNTIwNTRkZjU3NGYyMGJiN2MwYmRhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pg-Pb7wNJ5PzKw26eC_nvQDUiwlFMmgUL5o4BDNhtf8)

any logs at 02:00 on the 17th?
seems like something went wrong there

**Comment by antedebaas** [comment]
> Came here to also post this. `GetReportsFromMailbox command was already running.`

if you want me to figure out what happens i need more than this.

**Comment by tobsowo** [comment]
I honestly can't say what's happening but I plan to reinstall.

**Comment by antedebaas** [comment]
> I honestly can't say what's happening but I plan to reinstall.

A restart should remove the lock

**Comment by deanfourie1** [comment]
No a restart does not resolve it for me.

**Comment by antedebaas** [comment]
> > Was going well for a while, and then again :(
> > ![image](https://private-user-images.githubusercontent.com/71812804/349280896-c0e6f109-c492-4c23-81e2-133ea5de2198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDY3NDQsIm5iZiI6MTcyMTIwNjQ0NCwicGF0aCI6Ii83MTgxMjgwNC8zNDkyODA4OTYtYzBlNmYxMDktYzQ5Mi00YzIzLTgxZTItMTMzZWE1ZGUyMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4NTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYmNjYmIyNTIyYTVkZTQ5ZDJlY2IyNzQ2ODEzZDNkOGE1MzdlOWFlNTIwNTRkZjU3NGYyMGJiN2MwYmRhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pg-Pb7wNJ5PzKw26eC_nvQDUiwlFMmgUL5o4BDNhtf8)
> 
> any logs at 02:00 on the 17th? seems like something went wrong there


Also. What version are you running?

**Comment by deanfourie1** [comment]
I am running this image,

dmarc-reports-testing:sha-c4c254b, not actually sure where to find the version.

**Comment by antedebaas** [comment]
That’s a testing version. Please switch back to:

dmarc-reports:latest

**Comment by deanfourie1** [comment]
Ok, I have switched back to latest.

**Comment by antedebaas** [comment]
> Ok, I have switched back to latest.

And?

**Comment by deanfourie1** [comment]
Ok, just checked and same issue, 

![image](https://github.com/user-attachments/assets/0d7f6a60-ce43-473a-af5e-c266a140b9f9)

**Comment by antedebaas** [comment]
> > Was going well for a while, and then again :(
> > ![image](https://private-user-images.githubusercontent.com/71812804/349280896-c0e6f109-c492-4c23-81e2-133ea5de2198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDY3NDQsIm5iZiI6MTcyMTIwNjQ0NCwicGF0aCI6Ii83MTgxMjgwNC8zNDkyODA4OTYtYzBlNmYxMDktYzQ5Mi00YzIzLTgxZTItMTMzZWE1ZGUyMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4NTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYmNjYmIyNTIyYTVkZTQ5ZDJlY2IyNzQ2ODEzZDNkOGE1MzdlOWFlNTIwNTRkZjU3NGYyMGJiN2MwYmRhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pg-Pb7wNJ5PzKw26eC_nvQDUiwlFMmgUL5o4BDNhtf8)
> 
> any logs at 02:00 on the 17th? seems like something went wrong there

.

**Comment by deanfourie1** [comment]
This issue has been happening before the 17th.

**Comment by antedebaas** [comment]
Unless you give me more information (as I requested multiple times now) I can’t help

**Comment by deanfourie1** [comment]
Looks like the issue started on the 05/07

![image](https://github.com/user-attachments/assets/37d5cae0-6f3c-40eb-b1ce-504f51b3788e)

**Comment by antedebaas** [comment]
Final time. I need system logs from that moment. Something went wrong and I need the system logs from that moment.

**Comment by antedebaas** [comment]
Without additional ing
