### ISSUE TITLE
Template has absolute link to style.css

### ISSUE THREAD

**Issue by rvd0167** [antedebaas/DMARC-Reports#137]
File templates/base.html.twig line 8 has an absolute link to style.css
If you place Viesti-Reports into a subdirectory this css will not be loaded (or a wrong one is loaded).

    <link href="/style.css" rel="stylesheet">

If coorected in this twig, other pages have this problem.
The html is not consistent in this.

**Comment by antedebaas** [comment]
If you put it in a subdirectory you’ll brake more than that. You also break the meta-sts policy file.
This project is specifically intended to run on its own (sub) domain

**Comment by rvd0167** [comment]
I tackled this by simply changing templates/base.html.twig
The .htaccess is already setting the environment variable "BASE" for this.

`   <link href="/style.css" rel="stylesheet">
`
to:

`    <link href="{{ app.request.server.get('BASE') }}/style.css" rel="stylesheet">`
