### ISSUE TITLE
Check domain produces error

### ISSUE THREAD

**Issue by rvd0167** [antedebaas/DMARC-Reports#138]
**Describe the bug**
- When clicking Domains and click the Edit button an error apprears.

**Are you using the Docker image?**
- No

**Database used**
- MySQL/MariaDB

**Error Messages**
  Typed property Spatie\Dns\Records\TXT::$v must not be accessed before initialization

**Steps to Reproduce**
Try clicking any Edit button on the Domains menu

**Expected behavior**
No error ;-)

**Screenshots**
![image](https://github.com/user-attachments/assets/a5624c23-eb57-4729-a91b-de39eb8476a0)
![image](https://github.com/user-attachments/assets/12b6c376-9baa-40ca-a5e2-15ed2e83525a)

**Comment by antedebaas** [comment]
fixed in v1.19.0
