### ISSUE TITLE
README - php-zlib missing in Prerequisites

### ISSUE THREAD

**Issue by ondraknezour** [antedebaas/DMARC-Reports#140]
Processing of about half of my reports ended with error. Nothing useful in logs, only that message was flagged. Reports in IMAP mailbox looked fine, so I dived into database (SQLite, but not relevant here) to find that it is unknown report type and going deeper into sources I find usage of the gzopen() function, which is part of php-zlib extension, which at least on FreeBSD is not installed automatically as part of php package.

Please add php-zlib into Prerequisites section of README.

**Comment by antedebaas** [comment]
php-zlib is not a package on redhat based systems but ill add it to the list
