### ISSUE TITLE
Upgrade to 1.19 fails with Invalid platform version error 

### ISSUE THREAD

**Issue by webdeck** [antedebaas/DMARC-Reports#143]
**Describe the bug**

**Are you using the Docker image?**
- No

**Database used**
- PostgreSQL

**Database version used**
15.8

**Error Messages**
```
In InvalidPlatformVersion.php line 22:
                                                                               
  Invalid platform version "" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>".       
```

**Steps to Reproduce**
Please provide detailed steps to reproduce the problem:
1. Upgrade to 1.19 from 1.18
2. See this error both during upgrade and trying to access web page

**Expected behavior**
Upgrade works

**Comment by antedebaas** [comment]
- did you run update.sh? please provide more detail on what steps you took to upgrade
- could you provide more details? like a full log

**Comment by webdeck** [comment]
Upgrade output:
[upgrade.txt](https://github.com/user-attachments/files/16650199/upgrade.txt)

Where do I find the full log?  mta-sts/var/log is an empty directory.

**Comment by antedebaas** [comment]
so you ran update.sh?
what is your database connection string in .env.local? (remember to remove the password)

**Comment by webdeck** [comment]
Yes, I ran update.sh.  Everything has been working fine on previous versions. 

`DATABASE_URL="postgresql://dmarcsmtptlsreports:REDACTED@localhost:5432/dmarcsmtptlsreports"`

**Comment by antedebaas** [comment]
Not sure, but try and remove var/cache/prod under the project directory maybe that helps

**Comment by webdeck** [comment]
Same errors.

**Comment by antedebaas** [comment]
Maybe add ?serverVersion=15.8 at the end of the database string. Other than that I don’t know.
I personally use Postgres 16.1+ so if you can upgrade that could be an solution

**Comment by webdeck** [comment]
That fixed it.  Thank you!

**Comment by Routhinator** [comment]
I'm getting this with a new install of the docker image.. is there an undocumented required env var? The docker compose doesn't show anything for this

**Comment by Routhinator** [comment]
Digging further it appears that the `DATABASE_URL` env var is leveraged and unset, but there's nothing in the docs about this var, and nothing in the docker compose.. 

Are we supposed to have to set this variable @antedebaas ?

**Comment by Routhinator** [comment]
Ok I finally got this working. 

2 things that should be documented:

1. I think Symfony is the first and only app I've ever encountered that requires `postgresql` for it's DB string, most things I've used require `pgsql` or `postgres` - there should be a note in the docs about the accepted values for `DATABASE_TYPE`

2. It seems that currently, if using Postgres, all the `DATABASE_*` are useless, as you must manually craft the `DATABASE_URL` in order to add the version string at the end (I'm using PG 16.3 which is newer than the version @antedebaas mentions using) - This should be documented until a `DATABASE_SERVER_VERSION` var can be added that conditionally adds the `?serverVersion=$DATABASE_SERVER_VERSION` at the end of the `DATABASE_URL`

**Comment by Routhinator** [comment]
I guess the `postgresql` db type is more common than I have experience with, found out that CNPG's own `jdbc` and `uri` values in it's database secret have that in the string. The `uri` value is almost perfect for this, but it's missing the `?serverVersion` part.

So, if someone else comes across this and is deploying this via helm on kubernetes, it's possible to source the `uri` string from CNPG and just append the serverVersion into a new secret and source it from your deployment, like so:

```smarty
{{- $dbURL := ""}}
{{- $secret := ( lookup "v1" "Secret" .Release.Namespace ( printf "%s-%s" ( include "mail-server.fullname" . ) "viesti-reports-db-app" ) ) }}
{{- if $secret }}
{{- $dbURL = ( index $secret.data "uri" | b64dec ) }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-server.fullname" . }}-viesti-reports
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.viestiReports.settings.mail.username | b64enc | quote }}
  password: {{ .Values.viestiReports.settings.mail.password | b64enc | quote }}
  maxMindLicenseKey: {{ .Values.viestiReports.settings.maxMindLicenseKey | b64enc | quote }}
  dbURL: {{ ( printf "%s?serverVersion=%s" $dbURL .Values.global.database.serverVersion )  ) | b64enc | quote }}

```

**Comment by antedebaas** [comment]
What version are you using? Because DATABASE_TYPE is deprecated so I’m expecting you’re using an old version.

**Comment by Routhinator** [comment]
Im using the latest docker version based off the docker compose file main.

Pulled it for the first time ever yesterday, so can't have an old one. And those vars are still in use on main.

**Comment by Routhinator** [comment]
Just checked the hash, it matches 1.22.4

**Comment by antedebaas** [comment]
Check docker-compose.yml in the root directory. 
If that does not work please open a new ticket as this is unrelated to this issue

**Comment by Routhinator** [comment]
I have it working with my workaround, but to my previous point I _already_ looked at the docker-compose, and contrary to your statement, the docker-compose still explicitly sets `DATABASE_TYPE` - so if you did deprecate this variable the docker-compose and supporting documents have not been updated to indicate as such 

https://github.com/antedebaas/Viesti-Reports/blob/8380e2b4a9f0c3d79da89c745a4228878ffdba88/docker-compose.yml
