### ISSUE TITLE
Req. Change log page

### ISSUE THREAD

**Issue by rvd0167** [antedebaas/DMARC-Reports#149]
In the log the message "Processed 0 emails successfully." doesn't feel right.
Perhaps "No new reporting emails." seems more accurate.

--

You can only go up and down a single log page. 
![image](https://github.com/user-attachments/assets/64102ca8-4599-4144-b876-af49667d08cd)
But when the log consists of many pages, pagination can be made easier.
![image](https://github.com/user-attachments/assets/7b30abb5-2bc8-4c26-8847-e50aa93fc09c)

--

It is not possible to search within the log.
eg. search for errors or to show only entries with actual reports.

--

When reading a log detail, there is no Return button to go back to where you left off.
On mobile that is giving a problem, as the is no back-button (easily accessible) in the "browser".

**Comment by antedebaas** [comment]
The number 0 is a counter and I’m not changing that as it’s unneeded.
Logs are only useful for debugging and when you suspect something is wrong.
But you also want to know when it went well as that makes for a reliable fault message when there is one. 
I see no reason to spend a lot of time on logging. If you want to go back the browser already has a button for that.

**Comment by antedebaas** [comment]
You are free to submit a pull request if you want to make changes to this project

**Comment by rvd0167** [comment]
-not planned- Fair enough.  
Was just a request. As I do read logs for a living it would have made things easier.
:ok_hand: :bucket:

**Comment by antedebaas** [comment]
If this is important for you, see my previous comment 🙃

**Comment by rvd0167** [comment]
Important yes. Do I have enough spare time to fix it.... Not really.
But if I have some to spare, it would be a nice pastime.

**Comment by antedebaas** [comment]
No luck there
