### ISSUE TITLE
Domain not auto-created

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [antedebaas/DMARC-Reports#15]
Hey ante,

First of thanks for this nice interface!

I recently setup this system for the first time, after finishing the setup the **domains** table was not populated, this prevented reports from being parsed as well as mta-sts.txt files to be generated.
I ended up manually adding an entry directly in SQL.

As I'm not sure if this is an issue of documentation or that my specific setup is strange in a way that messed up the process I'm first of all opening a ticket, more than happy to create a PR to add the documentation.

The domains page does not seem to have an "add domain" button either so the only option I seemed to have was SQL.

Thanks!

**Comment by antedebaas** [comment]
No domains should be auto created for each domain it comes across.
I’ll have a look at this.

adding an add domain form is a good idea anyway

**Comment by Keeper-of-the-Keys** [comment]
If there is anything I can help with lmk

**Comment by antedebaas** [comment]
A pr is anyways welcome :)
Feel free to submit what you want to add

**Comment by antedebaas** [comment]
i checked the code and it should add the domains automatically.
do you get any errors in the logs?
either from your webserver or in de [project]/logs/prod/ directory
an add domain button will be added to the todo list :)

**Comment by Keeper-of-the-Keys** [comment]
Hey sorry for the delayed response, if the logs are in the apache logs then they were already rotated out :/ (though I remember there were kernel failures in parsing the e-mails because there was no domain entry), in the var/log/ directory of the project there is nothing there.

I'll try to do a clean setup and see what happens.

**Comment by Keeper-of-the-Keys** [comment]
Hey Ante,

I removed .env.local, dropped all tables in the database and ran update.sh to "reset" the installation after which I repeated my previous install steps and the domains table was not populated, var/log in the project folder contains nothing and the apache error log doesn't either.

Checking the DMARC mailbox in this state results in the following error:
```
[Sun Dec 17 21:46:42.855571 2023] [proxy_fcgi:error] [pid 249227:tid 140464590141120] [client ] AH01071: Got error 'PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sts_version' cannot be null"', referer: https://mta-sts.domain.tld/
```
Trying to retrieve the mta-sts.txt file results in the following error:
```
[Sun Dec 17 21:48:28.616520 2023] [proxy_fcgi:error] [pid 249228:tid 140464623711936] [client ] AH01071: Got error 'PHP message: [critical] Uncaught PHP Exception Error: "Call to a member function getMxRecords() on null" at /var/www/DMARC-SMTPTLS-Reports/src/Controller/PolicyFileController.php line 31'
```

Setup details - 
Debian 12, MariaDB 10, PHP 8.2 (using FPM)

**Comment by Keeper-of-the-Keys** [comment]
I read through the `app_setup` route and from what I understand (and I'm not very familiar with symfony so it could very well be I'm wrong) I don't see anywhere that a domain name is detected/inserted in the domains table.

If I understand the code correctly the domain addition is supposed to happen during the `CheckmailboxCommand` flow, but it seems the class `Domains` has some variables that have default values but are also assigned null and thus failing to add, I tried commenting out just the = something part to no avail though.

**Comment by Keeper-of-the-Keys** [comment]
The database schema and the code don't match in the sense that the database doesn't allow NULL values in fields that the code does allow it.

**Comment by antedebaas** [comment]
If you want to reset the project remove all tables too;
those are managed by the code and will get re-created during setup.
that's what the doctrine_migrations table is for.

domains are added for each mail message when needed because that's when a new domain can show up to the system.
but currently the project will probably fail because database schema versioning mismatching.

you can manually execute the migration by running the following command in the projects main directory
`php bin/console doctrine:migrations:migrate`

**Comment by Keeper-of-the-Keys** [comment]
Hey @antedebaas, that is what I did, the migrations work according to the installation wizard.

The way I understand things when adding a on demand domain no mailhost is set and in the database schema that is a not null column.

/Edit - as in I dropped all tables, I did not manually run the migrations I just used the initial setup.

**Comment by antedebaas** [comment]
yes i can reproduce it now.
fix incomming

**Comment by antedebaas** [comment]
should be fixed in v1.2.7 let me know if otherwise.

**Comment by Keeper-of-the-Keys** [comment]
The fix does not seem to have worked, the following error was returned:
```Got error 'PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "App\\Entity\\Domains::setMailhost(): Argument #1 ($mailhost) must be of type string, null given, called in /var/www/DMARC-SMTPTLS-Reports/src/Command/CheckmailboxCommand.php on line 84"; PHP message: [critical] Uncaught PHP Exception TypeError: "App\\Entity\\Domains::setMailhost(): Argument #1 ($mailhost) must be of type string, null given, called in /var/www/DMARC-SMTPTLS-Reports/src/Command/CheckmailboxCommand.php on line 84" at /var/www/DMARC-SMTPTLS-Reports/src/Entity/Domains.php line 197'```

I am not very familiar with the actual contents of dmarc reports but I suspect that the mailhost will have to be pulled from there if available.

**Comment by Keeper-of-the-Keys** [comment]
I just extracted one of the DMARC reports google sent me and it does not contain the mailhosts hostname so I don't think there would be an automatic way of detecting that, other options may be:
- dig mx records for the domain
- reverse lookup on source_ip (this however is very far from foolproof)

I don't know how this affects the rest of the code but maybe mailhost should be nullable and then fixed by the user in the domains section since there is no truly reliable way to extract this data based purely on the DMARC report.

**Comment by Keeper-of-the-Keys** [comment]
I on purpose added the domain with an empty string as mailhost (even though the column is not null '' is allowed :shrug:) and things don't seem to break in a conceivable way.

Your solution to add the domain as mailhost should also be OK, though maybe some warning that this needs to be changed after the fact, again not clear to me where the mailhost field is used.
