### ISSUE TITLE
Question: how to disable this log message

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#150]
Hi Ante,

I haven't filled the issue template, because there is no issue but just a question:

How can I disable this warning regarding a secondary mailbox?

![Screenshot 2024-08-26 082934](https://github.com/user-attachments/assets/e4852b1a-200c-4599-bd2e-315e8bb4fe11)

In fact I've never configured a second mailbox. This message appeared suddenly since one of the latest updates.

Many thanks!

Regards

Jürgen

**Comment by antedebaas** [comment]
yeah i added more details to logging but this is overkill.
ive already removed this one in the main branch. ill create a new release to everyone can have it :)

edit: v1.20.2

**Comment by bundyland** [comment]
Thanks a lot!!!!
