### ISSUE TITLE
SQL Error When Setting Up Viesti Reports

### ISSUE THREAD

**Issue by daygle** [antedebaas/DMARC-Reports#151]
**Describe the bug**
I am attempting to setup Viesti Reports on a clean Ubuntu 24.04 server. That said, I am unable to get past the setup screen '
Checking if database schema is up to date: Updates found.

It almost appears that Viesti Reports is trying to run a SQLlite script on my MySQL database although I have selected MySQL. See error below:-

**Are you using the Docker image?**
- No

**Database used**
- MySQL

**Webserver used (when not using docker) **
- Apache

**Error Messages**

From Apache2 Error Log:-

[Sun Sep 01 23:38:41.973640 2024] [php:notice] [pid 5855] [client 192.168.20.45:55411] [critical] Error thrown while running command "doctrine:migrations:migrate --no-interaction". Message: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTOINCREMENT NOT NULL, report_id INTEGER NOT NULL, source_ip VARCHAR(255) NOT N' at line 1", referer: http://192.168.20.204/public/index.php/setup

**Expected behavior**
Setup updates MySQL database correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/92967fa9-d5b3-4d07-87f8-14a082dd0823)

**Comment by antedebaas** [comment]
Try running php bin/console cache:clear and let me know if that fixes it

**Comment by daygle** [comment]
@antedebaas Thanks for getting back to me so fast.

Unfortunately that didn't fix it. I should mention that I have a separate mysql server which hosts the database - that shouldn't cause any issues right. I know it is able to connect.

**Comment by daygle** [comment]
@antedebaas I found out what is causing this. Basically removing the .env.test file allows me to update SQL.

Perhaps this needs to be removed from the repository?

**Comment by daygle** [comment]
@antedebaas Actually I had to also copy contents of .env.local and paste in to .env as well.

**Comment by daygle** [comment]
Actually, I'll close this case. Docker is so much easier than without docker.
