### ISSUE TITLE
[discussion/question] Should this project use css/js from CDNs?

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [antedebaas/DMARC-Reports#160]
I realized while testing some things that bootstrap css/js is being pulled from `cdn.jsdelivr.net` instead of being served directly by my server.

Would you be open to a PR that changes this? 

Using a CDN IMHO seems to be overkill here and opens a can of privacy and attack vectors.

**Comment by antedebaas** [comment]
No that was just because I was lazy. But I’m certainly open to eliminating the cdn’s
Please do try and use the latest available versions please (This is how it’s on my task list).

**Comment by antedebaas** [comment]
@Keeper-of-the-Keys im working on a whole new theme so you know.
ill be avoiding cdn's in it :)

**Comment by Keeper-of-the-Keys** [comment]
So I shouldn't bother doing a PR anymore? I probably have some time later today.

**Comment by antedebaas** [comment]
if you havent started i would not bother.
but if you have started its still usefull for the short term

**Comment by antedebaas** [comment]
New release. I longer uses a CDN

**Comment by Keeper-of-the-Keys** [comment]
Just upgraded, looks beautiful!

**Comment by Keeper-of-the-Keys** [comment]
There do seem to be some issues (if you were not aware of them and would like me to open ticket LMK):
1. How do I trigger viesti to retrieve new reports (I can't seem to find the retrieve reports button)?
2. When you click actions on a domain in the `domains` overview the context menu is displayed inside of the div of that list which is too small when there is only one domain thus effectively hiding the menu (though scrollbars appear which allow you to see it).
3. The same goes for `Users`.
4. The page that the documentation menu item links to seems to be broken.

BTW what are you using now? Is that tailwind under the hood?

**Comment by antedebaas** [comment]
1: that button has been gone quite a while now. it was problematic and only there because there was no way of changing the scheduled run which is the default see installservice.sh

2+3: ive seen the menu hiding its a bug in the ui im using (see https://tabler.io/) since its 1.0.0-beta21 i expect it to be fixed later on.

4: working on a temp website, but documentation will be completed in a later stage
