### ISSUE TITLE
Automatic updating task fails (type incompatibility) and don't recover itself

### ISSUE THREAD

**Issue by ceskyDJ** [antedebaas/DMARC-Reports#162]
### Issue Template

**No relevant issue exists**
I looked up the issue list and found no similar issue.

**Describe the bug**
For some reason, there was a type incompatibility, and the automatic task for reading reports from the email account failed. In the dashboard, I see information about already running command:
![image](https://github.com/user-attachments/assets/fe591a14-aa1a-4228-ba22-e4338eae9313)

When I went a few reports back in history, I found that some uncaught exception should cause it:
![image](https://github.com/user-attachments/assets/a937a1c5-9478-4a23-90e0-4683a2484a95)

I see a pretty big problem here. How could some uncaught exceptions in some running tasks break future runs? I think that running a task with an error like this should be adequately killed so that when the following cron job runs the task again, it has a chance to run properly.

**Are you using the Docker image?**
- Yes

**Database used**
- MariaDB

**Database version used**
11.5.2

**Error Messages**
The unhandled exception I talked about is this (according to information obtained from error message detail in GUI):
`App\Repository\LogsRepository::try_unserialize(): Return value must be of type array, false returned`

**Steps to Reproduce**
I don't know. I changed nothing, do nothing. I just opened the dashboard and saw the error messages I presented above.

**Expected behavior**
There are two things:
1. The exception should be caught / the error should be fixed in case of a bug in the code.
2. Running tasks should be killed in case of error so the following cron job can run a new task that tries the report synchronization again (and possibly succeeds).

**Additional context**
If you need something more, just let me know and I will add it.

**Comment by ceskyDJ** [comment]
Oh, I forgot to mention that I tried to restart the Docker compose stack running Viesti reports, but the issue still exists. I tried the restart (`docker compose restart`) between 12:00 and 13:00. I expected the cron job at 13:00 would end up fine, but according to the error messages, it's still the same.

**Comment by antedebaas** [comment]
Yeah that implementation needs work. I’m already reworked it but it’s not ready for release yet.
For now you can run the command
`php /var/www/html/bin/console app:removemaillock` in the docker container to release the mail lock so processing continues again

**Comment by ceskyDJ** [comment]
> For now you can run the command
> `php /var/www/html/bin/console app:removemaillock` in the docker container to release the mail lock so processing continues again

It helped, thanks! I have a few success messages in the log.

**Comment by antedebaas** [comment]
I released a new version today with quite a few improvements. 
one of them being better error handling when the command fails. You might want to update to the latest version.

**Comment by ceskyDJ** [comment]
Thanks a lot! As I have noticed in a notification, Watchtower has already done it. I'm looking forward to the changes in UI as you promised in the release log 😀!

**Comment by antedebaas** [comment]
When it’s updated you should immediately see the new webui

**Comment by ceskyDJ** [comment]
I took a look when I was on my way to the faculty. It looks pretty good but has its issues. I'll try to report at least some of them when I have a little free time for that.

**Comment by antedebaas** [comment]
Sure. Please do
