### ISSUE TITLE
Environment variable not found: "PUSHOVER_API_KEY"

### ISSUE THREAD

**Issue by webdeck** [antedebaas/DMARC-Reports#165]
**Describe the bug**
Log shows error when getting reports from mailbox: Environment variable not found: "PUSHOVER_API_KEY"

**Are you using the Docker image?**
- No

**Database used**
- PostgreSQL

**Webserver used (when not using docker) **
- Nginx

**Database version used**
15.8

**Error Messages**
```
Exception in GetReportsFromMailbox command

STATE | REPORT TYPE | MESSAGE | EXTERNAL MAILID |  
-- | -- | -- | -- | --
  | Other | Environment variable not found: "PUSHOVER_API_KEY".
```

**Steps to Reproduce**
Please provide -detailed- steps to reproduce the problem:
1. Go to Main page
2. Click on Details for latest log message
3. See error

**Expected behavior**
No errors

**Comment by antedebaas** [comment]
ugh
v.1.21.3 :)
