### ISSUE TITLE
Documentation link points to domain that does not exist

### ISSUE THREAD

**Issue by webdeck** [antedebaas/DMARC-Reports#167]
The Documentation link points to `https://docs.viestireports.com/` but the domain name does not exist.

**Comment by antedebaas** [comment]
yes, that one is comming later

**Comment by antedebaas** [comment]
There is now some contents. But actual documentation will be added over time

**Comment by webdeck** [comment]
It briefly flashes a Uncaught Runtime Errors with a long stack trace and then switches to a blank page.

**Comment by antedebaas** [comment]
yeah i broke it again. will work on it later

**Comment by antedebaas** [comment]
I have some working documentation page now.
Extended documentation will be worked on over time you can also help out in https://github.com/antedebaas/Viesti-Reports-Docs
Documentation will be written down using markdown so it’s a low entry level
