### ISSUE TITLE
No Reports are 

### ISSUE THREAD

**Issue by roburb** [antedebaas/DMARC-Reports#17]
Hi,
I have found you project and it looks nice => I have installed.
The installation was without any issue.
The .env.local file was created, the database too.
I have create user in last step, all ok up to now.
I have placed the the installation directly to mta-sts.domain.ext => the mta-sts.txt file is correct
The extra email box works.

The issue is: the reports are not parsed. 
There is always similar entry in log:

_Mailbox checked: 0 new emails (0 domains, 0 mx), 0 new dmarc reports (0 records, 0 results), 0 new smtptls reports (0 policies, 0 mxmapping, 0 failure details)_

It is not correct, the email are moved from new to cur subfolder of maildir.
There is no error in php log file.
There is no log file in dir project_folder/var/log.
I don't know where I can find next hint, what is wrong.

Thank you
Best regards
Robert

**Comment by antedebaas** [comment]
Are the emails marked as unread?
Since it sees 0 email I’m guessing it does not find the emails. 
the project only looks as unread emails and marks them as read

**Comment by roburb** [comment]
Hi,
thank you. You are right the emails ware not found. 
It works now, or at least it seams so :-)
