### ISSUE TITLE
Bad UX of ”Actions“ option switches

### ISSUE THREAD

**Issue by ceskyDJ** [antedebaas/DMARC-Reports#171]
All tables with data have operation buttons hidden under ”Actions“ option switch. So, you need to click/tap more times than it's necessary. As least for places, where there is just one operation (e.g. ”Detail“) it just doesn't make sense.

**Comment by antedebaas** [comment]
It’s a uniform way to present the UI.
For some pages more features are added and I don’t want every page to work differently.
That’s why I decided to have it this way

**Comment by ceskyDJ** [comment]
Ok, I get it. So, why don't use icons for these actions on all the places? Maybe the details could be opened via clicking on the table row, too. I don't say this is some critical problem, but it could bring a little more user friendly interface. I don't know, how icon buttons (on smaller devices and icon + text on bigger ones) would work here, but I have pretty positive experience with this solution elsewhere.

**Comment by antedebaas** [comment]
Because I decided to do it this way. I don’t want buttons everywhere.

if you want to make changes you’re welcome to submit a pull request with the suggested changes. I will evaluate it then.
