### ISSUE TITLE
Domain names are missing from tables with the latest reports

### ISSUE THREAD

**Issue by ceskyDJ** [antedebaas/DMARC-Reports#172]
There is no domain name column in the tables ”Latest DMARC reports“ and ”Latest SMTP-TLS reports“. So, it says nothing without going to the detail subpage.

Device: Samsung Galaxy S22
Browser: Brave
OS: Android 14

**Comment by antedebaas** [comment]
There is very limited screen space on mobile devices and I had to prioritize.
I think it’s better to show results than a domain name.
This way you at least see it when something is wrong.

**Comment by ceskyDJ** [comment]
I see. But what about to show just 2 columns — domain name with spf and dkim badges (see Bootstrap badges) and actions? I think ID isn't important here (it says me nothing about the report) and if you show SPF and DKIM results just as badges, you can save some space. Number of messages isn't too important here, too, I think. I just want to know if DMARC reports for my domains looks good or not in the first shot. If I need details, I just open the detail. But, yeah, it's my point of view, of course, you can have completely different one. I just want you to think about it a bit.

**Comment by antedebaas** [comment]
I decided on this design.
if you want to make changes you’re welcome to submit a pull request with the suggested changes. I will evaluate it then.
