### ISSUE TITLE
Don't show DMARC disposition if DMARC test succeed

### ISSUE THREAD

**Issue by ceskyDJ** [antedebaas/DMARC-Reports#173]
In case of success DMARC test, the disposition is always ”none“ and generally gives as no information. Some users could be confused by it, that's all it could provide in this case.

Of course, in case of fail, it's very important to show it.

**Comment by antedebaas** [comment]
Does it really hurt to have all the details on the details page?

**Comment by ceskyDJ** [comment]
I don't know if it's that bad, but it distracts my attention and mainly makes me study the meaning of this DMARC report item unless I need it (all my DMARC reports are green).

So, it's not a priority, but if you have some time for it…

**Comment by antedebaas** [comment]
I’ve decided to do it this way.
if you want to make changes you’re welcome to submit a pull request with the suggested changes. I will evaluate it then.

**Comment by ceskyDJ** [comment]
Ok, no problem. It's your project, so all I can do is propose things. I'm sorry, but the chance for my direct contribution here is minimal. I don't have enough time for it.

I can offer a translation to Czech if you want. That's about what I can place on my schedule.
