### ISSUE TITLE
Error on upgrade

### ISSUE THREAD

**Issue by WebCodePoet** [antedebaas/DMARC-Reports#174]
I tried to upgrade today, I get following errors:

[notice] Migrating up to DoctrineMigrations\Version20241013152145
[notice] CREATE TABLE config (name VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 
[critical] Error thrown while running command "doctrine:migrations:migrate --no-interaction --query-time --all-or-nothing". Message: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist"

In ExceptionConverter.php line 91:
                                                                                                            
  An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 S  
  AVEPOINT DOCTRINE_2 does not exist                                                                        
                                                                                                            

In Exception.php line 28:
                                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist  
                                                                                               

In Connection.php line 27:
                                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist  
                                                                                               

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]

[critical] Error thrown while running command "app:migrateenvvars". Message: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.type' in 'field list'"

In ExceptionConverter.php line 52:
                                                                                                            
  An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c  
  0_.type' in 'field list'                                                                                  
                                                                                                            

In Exception.php line 28:
                                                                                     
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.type' in 'field list'  
                                                                                     

In Statement.php line 55:
                                                                                     
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.type' in 'field list'  
                                                                                     

app:migrateenvvars

done

**Comment by antedebaas** [comment]
Please use the issue template so I know essential environment information

**Comment by WebCodePoet** [comment]
@antedebaas 

### Issue Template

**Describe the bug**
I cant finish the upgrade process.

**Are you using the Docker image?**
- No

**Database used**
- MariaDB

**Webserver used (when not using docker) **
- Nginx with PHP-FPM 8.3

**Database version used**
10.11.8

**Operatingsystem**
Ubuntu 24.04 with latest Plesk

**Error Messages**
[notice] Migrating up to DoctrineMigrations\Version20241013152145
[notice] CREATE TABLE config (name VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4
[critical] Error thrown while running command "doctrine:migrations:migrate --no-interaction --query-time --all-or-nothing". Message: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist"
In ExceptionConverter.php line 91:
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 S
AVEPOINT DOCTRINE_2 does not exist
In Exception.php line 28:
SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist
In Connection.php line 27:
SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist
doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] []
[critical] Error thrown while running command "app:migrateenvvars". Message: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.type' in 'field list'"
In ExceptionConverter.php line 52:
An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c
0_.type' in 'field list'
In Exception.php line 28:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.type' in 'field list'
In Statement.php line 55:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.type' in 'field list'
app:migrateenvvars
done

**Steps to Reproduce**
Please provide -detailed- steps to reproduce the problem:
1. Upload all files to the httpdocs dir
2. Set chmod +x to sh and bin files
3. Run upgrade.sh
4. See error

**Expected behavior**
Working upgrade

**Comment by WebCodePoet** [comment]
I got it now running by altering the php to /opt/plesk/php/8.3/bin/php in update.sh and upgrade.sh,
I also changed composer install to /opt/plesk/php/8.3/bin/php /usr/lib/plesk-9.0/composer.phar install,
Than I run the mysql migrations by hand in PHPMyAdmin, because direct execution did not worked.

No everything's looks to be working as expected.

Kind Reagds.
