### ISSUE TITLE
update.sh shows error (again)

### ISSUE THREAD

**Issue by WebCodePoet** [antedebaas/DMARC-Reports#175]
Issue Template

Describe the bug
update.sh shows error, no migration

Are you using the Docker image?
No

Database used
MariaDB

**Webserver used (when not using docker) **
Nginx with PHP-FPM 8.3

Database version used
10.11.8

Operatingsystem
Ubuntu 24.04 with latest Plesk

Error Messages

run migrations
[notice] Migrating up to DoctrineMigrations\Version20241013152145
[notice] CREATE TABLE config (name VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 
[critical] Error thrown while running command "doctrine:migrations:migrate --no-interaction --query-time --all-or-nothing". Message: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist"

In ExceptionConverter.php line 91:
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist
In Exception.php line 28:
SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist
In Connection.php line 27:
SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist
doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]

Steps to Reproduce
Run upgrade.sh
See error

/setup shows

There are new schema updates available
The following migrations have not been processed:

DoctrineMigrations\Version20240819175623
DoctrineMigrations\Version20241013152145
DoctrineMigrations\Version20240617165805
DoctrineMigrations\Version20240929171133
DoctrineMigrations\Version20240619204435

Expected behavior
Working update.sh

**Comment by antedebaas** [comment]
You ran sql commands by hand in the last issue thus breaking the migrations. To fix this you would need to reinitialize the database and not do any manual modifications

**Comment by WebCodePoet** [comment]
I created a new database, thanks.
