### ISSUE TITLE
FeatureRequest: Mailbox Folder

### ISSUE THREAD

**Issue by KGBist2000** [antedebaas/DMARC-Reports#19]
Please add a posibility to select inside an Mailbox an imap folder for TLS Reports and one for dmarc Reports. 

It should be possible to select separat imap Folders.

**Comment by antedebaas** [comment]
I don’t understand why.

mail comes in at the inbox so all unprocessed mails should be there.
Moving them after processing seems more logical to me if you want to archive hem.

**Comment by KGBist2000** [comment]
Hi, thank you for your reply. Please find the usecase, hoply it is then easier to follow:

- I am using the same mailbox for different reporting to my server e.g. server@domain.com with different alias like
  - dmarc@domain.com for dmarc reports
  - tlsreport@domain.com for tls-reports
  - abuse@domain.com for abuse reports
  - ...
  -
2. my Mailserver is desined to sort base on the adressed alias the income reports in different imap folders inside the one mailbox server@domain.com
- imap-folder: dmarc for dmarc@domain.com
- imap-folder: abuse for abuse@domain.com
- ....
3. This is helpfull to use only one mailbox and do not create for different report-parser several mailboxes.
4. At the end the function to transfer the parsed report into an archive imap folder will be also very helpfull for deep-checks if need to debug something.

**Comment by antedebaas** [comment]
I’ve given this some thought and decided that I won’t implement this in the short term.
I would however like to keep this open so I can think about it some more in the long term

**Comment by rschenk0** [comment]
I would appreciate it, too. So you can have one administrative mailbox for multiple purposes and have all important reporting in one account for human control.

**Comment by antedebaas** [comment]
implemented in 1.10 :)
you can run the update script and add the following to your .env.local

MAILBOX_PATH="__MAILBOX_PATH_TO_YOUR_DMARC_SUBFOLDER__"

MAILBOX2_ENABLED="true"
MAILBOX2_CONNECTION="__HOST__:993/imap/ssl"
MAILBOX2_USERNAME="__USERNAME__"
MAILBOX2_PASSWORD="__PASSWORD__"
MAILBOX_PATH="__MAILBOX_PATH_TO_YOUR_SMTPTLS_SUBFOLDER__"
