### ISSUE TITLE
TLS Report and Docker Installation

### ISSUE THREAD

**Issue by tobsowo** [antedebaas/DMARC-Reports#2]
Thank you for making this public,  do you plan to add TLS Report and make the installation possible via Docker?

**Comment by antedebaas** [comment]
I will look into the TLS Reporting.
as for docker ill think about it. shouldn't be to hard

**Comment by tobsowo** [comment]
Great. Thank you.

**Comment by antedebaas** [comment]
@tobsowo ive just added the MTA-STS processing to the main branch.
I’ll update the readme etc later but it looks for them in the same mailbox as the dmarc reports.

the docker part is still in development.

**Comment by tobsowo** [comment]
Thank you so much.
I'll appreciate the update.

**Comment by antedebaas** [comment]
i found i had a few more things i did not see before. so i reverted the SMTP TLS update for now. 
turns out it was incomplete

**Comment by tobsowo** [comment]
Alright, please take your time.

**Comment by antedebaas** [comment]
i will :)

**Comment by antedebaas** [comment]
The TLS Reporting is now done :)

**Comment by tobsowo** [comment]
Great.
Thank you.

**Comment by antedebaas** [comment]
@tobsowo there you go :)
https://hub.docker.com/repository/docker/antedebaas/dmarc-reports/general

there is a docker compose in the main branch as an example

**Comment by tobsowo** [comment]
Whaoooo @antedebaas 
Thank you.

**Comment by tobsowo** [comment]
Is there a docker-compose.yml file?

**Comment by antedebaas** [comment]
Right here : https://github.com/antedebaas/DMARC-Reports/blob/main/docker-compose.yml

**Comment by tobsowo** [comment]
Thank you so much

**Comment by tobsowo** [comment]
Please I got stuck here and do not know how to proceed
![image](https://github.com/antedebaas/DMARC-Reports/assets/5642737/a5801a9b-ccfe-4281-aff7-9231e47a29dc)

**Comment by antedebaas** [comment]
Did you press the update database button?
And if so I’m guessing it doesn’t proceed?

i tested here and if you remove the volumes section from the docker compose it should work again

**Comment by tobsowo** [comment]
Yes, I click the button and didn't proceed.
I'll try with removing the volume but will that nor affect volume persistent in a case of restart?

Also, do I need to include database in the docker-compose file?

**Comment by antedebaas** [comment]
you will have to re create the docker containers. and yes it needs (mysql) a database

**Comment by tobsowo** [comment]
Alright, thank you.

**Comment by tobsowo** [comment]
I still experience the same issue. Kindly find my docker-compose file below.


version: "2"
services:
  dmarc-reports:
    image: antedebaas/dmarc-reports:latest
    container_name: dmarc_tls_report
    depends_on:
      - db
    ports:
        - 0.0.0.0:8080:8080
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: dmarcreports
      DATABASE_USER: user
      DATABASE_PASSWORD: password 1
      MAILER_HOST: mail.example.com
      MAILER_SMTPPORT: 25
      MAILER_IMAPPORT: 993
      MAILER_USER: mailer
      MAILER_PASSWORD: password3
    restart: unless-stopped

  db:
    image: ghcr.io/linuxserver/mariadb:alpine
    container_name: dmarc_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Lagos
      - MYSQL_DATABASE=dmarcreports
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password1
      - MYSQL_ROOT_PASSWORD=password2
    volumes:
      - ./database:/config
    ports:
      - 3306
    restart: unless-stopped

**Comment by antedebaas** [comment]
i tested it with the official mariadb image and this works.
here is my docker-compose

version: "2"
services:
  dmarc-reports:
    image: antedebaas/dmarc-reports:latest
    ports:
        - 0.0.0.0:8080:8080
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: dmarc_db
      DATABASE_PORT: 3306
      DATABASE_NAME: dmarcreports
      DATABASE_USER: dmarcreports
      DATABASE_PASSWORD: [password_1]
      MAILER_HOST: imap.your.host
      MAILER_SMTPPORT: 25
      MAILER_IMAPPORT: 993
      MAILER_USER: [mailbox_username]
      MAILER_PASSWORD: [mailbox_password]
    restart: unless-stopped
  db:
    image: mariadb:latest
    container_name: dmarc_db
    environment:
      MYSQL_DATABASE: dmarcreports
      MYSQL_USER: dmarcreports
      MYSQL_PASSWORD: [password_1]
      MYSQL_ROOT_PASSWORD: [password_2]
    ports:
      - 3306
    restart: unless-stopped

**Comment by tobsowo** [comment]
Thank you. I'll check again.

**Comment by tobsowo** [comment]
Thank you, it worked!

**Comment by tobsowo** [comment]
Can the report be picked from the previous mailor it is only new reports that will be picked?

**Comment by antedebaas** [comment]
all unread messages will be processed :)
it will mark them as read automatically

**Comment by tobsowo** [comment]
I have some unread messages but they are not showing up on the dashboard.
Is there a cron job running, maybe I have to wait for it to run?
![image](https://github.com/antedebaas/DMARC-Reports/assets/5642737/236e92d7-f848-4a6f-9aa0-29daa800a77d)

**Comment by antedebaas** [comment]
There is a cron job in the docker container that runs once a day at midnight

**Comment by tobsowo** [comment]
Alright, preferably will it be possible to have it run every 6 hours, or can I change that myself?

- Also, I noticed that there was a 500 error for a new account although it was successfully created but User did not receive a welcome email to activate the account.
- Secondly, as an admin can I manually add users from the User menu?
- Thirdly, can there be a password reset option on login?
- Option to sort by: result, date, organization, reporter organization, domain
- Lastly, is it possible to assign a specific domain to a user for viewing without having access to all records?

I can create a new issue for this if you feel like it.

Thank you for the amazing work.

**Comment by antedebaas** [comment]
> Alright, preferably will it be possible to have it run every 6 hours, or can I change that myself?
The docker version is scheduled to run once a day. that should be enough. you can always fork this repo and change the docker image.
I am planning to add a button so you can run it at will.
> 
>     * Also, I noticed that there was a 500 error for a new account although it was successfully created but User did not receive a welcome email to activate the account.
then you mis-configured the mail settings.
> 
>     * Secondly, as an admin can I manually add users from the User menu?
not planned for now. if this project gets more vibe i might consider it
> 
>     * Thirdly, can there be a password reset option on login?
not planned for now. if this project gets more vibe i might consider it.
for now the the admin can reset it
> 
>     * Option to sort by: result, date, organization, reporter organization, domain
not planned for now. if this project gets more vibe i might consider it
> 
>     * Lastly, is it possible to assign a specific domain to a user for viewing without having access to all records?
you can edit existing users. in the edit screen you can set rights to known domains.
those are the only ones they can see. by default they see nothing.
> 
> 
> I can create a new issue for this if you feel like it.
> 
> Thank you for the amazing work.

**Comment by tobsowo** [comment]
Thank you for your reply.

Not sure what I'm doing wrong with the email settings because I'm still not able to view reports and it's over 24 hours after installation.

Is there private channel I can message you and share my configuration file with you?

**Comment by tobsowo** [comment]
Thank you for the update, the "check mail now" is a good addition.

- I am still unable to access email but I noticed that when I use **mail** instead of **mail.domain.tld** for **MAILER_HOST** the "500 Internal Server Error" stopped but it is still unable to fetch emails.
- My mail server uses **587** but I tried changing it to **MAILER_SMTPPORT: 25** it still did not work.
- When I tried to create a new user although the user is created it still shows "500 Internal Server Error" and it is not activated.

Below is my docker-compose.yml file

version: "2"
services:
  dmarc-reports:
    image: antedebaas/dmarc-reports:latest
    container_name: dmarc_tls_report
    ports:
        - 0.0.0.0:8080:8080
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: dmarcreports
      DATABASE_USER: dmarc
      DATABASE_PASSWORD: PassWord1
      MAILER_HOST: mail
      MAILER_SMTPPORT: 587
      MAILER_IMAPPORT: 993
      MAILER_USER: inbox@domain.tld
      MAILER_PASSWORD: InboxPassword
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: dmarc_db
    environment:
      - MYSQL_DATABASE=dmarcreports
      - MYSQL_USER=dmarc
      - MYSQL_PASSWORD=PassWord1
      - MYSQL_ROOT_PASSWORD=RootPassword
    volumes:
      - ./dmarc-report-db:/var/lib/mysql

    ports:
      - 3306
    restart: unless-stopped

**Comment by tobsowo** [comment]
**Logs**

When I used MAILER_HOST: mail the log threw an error of no host like mail but when I changed to mail.domain.tld I get the logs below


```
NOTICE: PHP message: [critical] Uncaught PHP Exception Error: "Class "ZipArchive" not found" at /var/www/html/src/Command/CheckmailboxCommand.php line 282
192.168.1.2 - - [26/Sep/2023:17:23:15 +0000] "GET /reports/checkmailnow HTTP/1.1" 500 1027 "https://dmarc.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.36" "105.112.31.189, 141.101.99.188" 0.595 0.595 . -
2023/09/26 17:23:15 [error] 15#15: *11 FastCGI sent in stderr: "PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "Class "ZipArchive" not found"PHP message: [critical] Uncaught PHP Exception Error: "Class "ZipArchive" not found" at /var/www/html/src/Command/CheckmailboxCommand.php line 282" while reading response header from upstream, client: 192.168.1.2, server: _, request: "GET /reports/checkmailnow HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "report.dmarc.domain.tld", referrer: "https://report.dmarc.domain.tld/"
NOTICE: PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "Class "ZipArchive" not found"
```

**Comment by antedebaas** [comment]
> **Logs**
> 
> When I used MAILER_HOST: mail the log threw an error of no host like mail but when I changed to mail.domain.tld I get the logs below
> 
> ```
> NOTICE: PHP message: [critical] Uncaught PHP Exception Error: "Class "ZipArchive" not found" at /var/www/html/src/Command/CheckmailboxCommand.php line 282
> 192.168.1.2 - - [26/Sep/2023:17:23:15 +0000] "GET /reports/checkmailnow HTTP/1.1" 500 1027 "https://dmarc.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.36" "105.112.31.189, 141.101.99.188" 0.595 0.595 . -
> 2023/09/26 17:23:15 [error] 15#15: *11 FastCGI sent in stderr: "PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "Class "ZipArchive" not found"PHP message: [critical] Uncaught PHP Exception Error: "Class "ZipArchive" not found" at /var/www/html/src/Command/CheckmailboxCommand.php line 282" while reading response header from upstream, client: 192.168.1.2, server: _, request: "GET /reports/checkmailnow HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "report.dmarc.domain.tld", referrer: "https://report.dmarc.domain.tld/"
> NOTICE: PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "Class "ZipArchive" not found"
> ```
That’s probably an missing package. I’ll check that soon

**Comment by antedebaas** [comment]
@tobsowo should be fixed now

**Comment by tobsowo** [comment]
Yea! Worked as a champ.
Thank you.

One more thing please, the user editing can autofill be removed and also be able to edit without having to change login details if I only needed to update the roles.

**Comment by antedebaas** [comment]
Great to hear.
As for the request please open a new issue
