### ISSUE TITLE
Checkmail button timeout

### ISSUE THREAD

**Issue by tobsowo** [antedebaas/DMARC-Reports#22]
When I use the Check Mail Now button, I run into Gateway time-out.

I see this error in log.

Port 143
`NOTICE: PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "["TLS\/SSL failure for mail.mailserver.com: SSL negotiation failed"]"`

Port 993
`NOTICE: PHP message: [critical] Error thrown while running command "app:checkmailbox". Message: "["IMAP SERVER BUG (invalid challenge): \"\"","Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (server response)"]" `
Please note that Port 143 works well with mail clients that are connected to the same mailbox.

I got this response from the mail server developer

```
If it works with your mail clients then it looks like an issue with your PHP code
Probably the TLS library is using a deprecated ciphersuite and it is not possible to negotiate a TLS connection
```

**Comment by antedebaas** [comment]
@tobsowo the code for the imap connection has not changed in the last few releases.
Please check other changes you did in your environment
