### ISSUE TITLE
Feature request: amd/arm multiarch support (docker)

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#25]
Hi guys,

If it should be possible at some point, I would be really excited about support for ARM architecture to run the dmarc-smtptls docker image also on the raspberry pi or ARM Hetzner server.

Many thanks and keep up the good work.

Kind regards from Spain...

**Comment by antedebaas** [comment]
Thats a good idea;
could you try this image?

antedebaas/dmarc-reports:1.4.0-test

I don’t have an arm device myself but none of my code is platform specific anyway so is just the os and it’s packages.
If this works I’ll put it to the main version

**Comment by bundyland** [comment]
Wow, that was fast!!!!

I have deployed it on my ARM Hetzner server behind a nginx reverse proxy and it's working like a charm.

I have just noticed one small thing (but I guess this is not really arm related):

There is a "one hour" time difference between my local time and the time stamp in the logs. In fact the logs are one hour back.
Well, this is just cosmetic and not dramatic, but would be nice if we could solve that sometime.

Finally I can avoid using third-party services and better manage all reporting stuff myself self hosted.

**Thanks a lot!!!!**

**Comment by antedebaas** [comment]
You were in luck, i was working on the project this morning anyway 😄 
the time difference is known, however email validation will not work if the timezone it not set to UTC (see issue #12)

**Comment by bundyland** [comment]
Uff, I wish I would have the same luck if I play Eurojackpot. ;-)

I don't care about the email validation issue as I don't need additional users.

Thanks once again for that great piece of software.

All the best...

**Comment by antedebaas** [comment]
@bundyland the multiplatform image is now available as antedebaas/dmarc-reports:1.4.0 (and higher)

**Comment by bundyland** [comment]
> @bundyland the multiplatform image is now available as antedebaas/dmarc-reports:1.4.0 (and higher)

Thank you so very much! Great job!
