### ISSUE TITLE
Make Dmarc Reporter available as Subsite (e.g. Domain/dmarcreports)

### ISSUE THREAD

**Issue by DerLinkman** [antedebaas/DMARC-Reports#26]
Hi!

I'm currently trying to implement your software in some kind within the mailcow: dockerized stack as it would fit kinda nicely to the project in general.

However i came across the "issue" that the dmarc parser is always redirecting itself to / not a subsite. I can setup a nginx location for the dmarcparser but the redirects done by the dmarc parser will fail.

Maybe i'm just to dumb or something is hardcoded.

The example Location:
```
  location /dmarcparser/ {
    proxy_pass       http://dmarcparser:8080/;
    proxy_set_header Host      $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
  }
```

Nice work, keep going :)

**Comment by antedebaas** [comment]
@DerLinkman yes. This project needs its own vhost to work.
The point is that it needs a vhost anyway for the SMTP TLS reports.
To me it feels unlogical to add support for a sub folder when that means that half its functionality will not work in such a setup anyway. 
Thus I’ve decided not to put in the effort myself.

**Comment by DerLinkman** [comment]
Hi @antedebaas!

Thanks for reply.

Yeah that is no problem then i'll simply implement it on a different approach. That is no problem at all.
