### ISSUE TITLE
Feature Request: change mail fetch cron job through environment (docker)

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#27]
Hi @antedebaas,

I'm sorry if I'm bothering you again today with a feature request.

Would it be maybe possible to set the time of the cron job for fetching new mails through the env. of the docker compose file instead of hardcoding it in the docker image? For example something like:  `CRON_JOB: 0 1 * * *`.
That would give more flexibility and everyone could decide at what time and how often the cron job should run. 

Alternatively asked: is there a docker compose exec command to run the cron job manually (for example through a script)?

Once again many thanks for your great work.

Cheers..

**Comment by antedebaas** [comment]
the way its implemented right now is that you can use the "Check mailbox now" button in the top right corner (as admin user) to trigger an instant check.
i could change the daily schedule (its been asked before) but personally i don't see the importance.
generally services report only once a day so don't expect google (for example) to report faster when you check your mailbox more often.

**Comment by bundyland** [comment]
Alright. Thank you very much. Let's leave it as it is.

I will play around with Docker to see if I can manually trigger the cron job somehow.

**Comment by bundyland** [comment]
Found it:

`docker exec -t dmarc-web-1 php /var/www/html/bin/console app:checkmailbox`

For people who want to run the automatic mailfetch more often (or at a different time): simply run the above command via cron (preferably as a bash script).

Cheers...
