### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by devkzidane** [antedebaas/DMARC-Reports#29]
How can i configure nginx to work with this project?

It seems it relies on .htaccess and nginx has no support for it.

I've tried the default Symfony nginx configuration with no avail. Getting 404 on /setup page.

Any help is appreciated!

**Comment by antedebaas** [comment]
The docker version uses nginx so I have it working in it.
Check dockerfiles/etc/nginx/nginx.conf
Let me know if that helps!

**Comment by devkzidane** [comment]
Now it's giving "HTTP 500" with
`Uncaught PHP Exception Symfony\Component\Security\Core\Exception\InvalidArgumentException: "A non-empty secret is required." at SignatureHasher.php line 42`

In PHP-FPM error log.

I've tried generating symfony secret keys, but it didn't help.

**Comment by devkzidane** [comment]
Working now after adding a secret key to .env. going through the setup still.

**Comment by devkzidane** [comment]
I got it working. 

Is it safe to use this parameter in .env "DELETE_PROCESSED_MAILS=" ? and what to set it to, "yes"?

**Comment by devkzidane** [comment]
Note that installservice.sh is also failing, I've ran it manually.
```
`installservice.sh: line 14: syntax error near unexpected token fi'

`installservice.sh: line 2: [: -v: binary operator expected`
```

**Comment by devkzidane** [comment]
Sorry, another thing, 3- How do i pull updates without breaking the site?

**Comment by antedebaas** [comment]
DELETE_PROCESSED_MAILS=true will delete emails after being processed. if you set it to false it will mark them as read and let them be. only unread mails are processed.

the installservice.sh should be working fine but the only thing it does is copy and modify some files.
check out:
- systemd/dmarcmailcheck.service which should be edited and copied to /usr/lib/systemd/system/dmarcmailcheck.service
- systemd/dmarcmailcheck.timer which should be copied to /usr/lib/systemd/system/dmarcmailcheck.timer
- then run systemctl daemon-reload
- and then run systemctl start dmarcmailcheck.timer

the latest modification to the update script is that it looks for the latest release tag and pulls that one so you will not break the site by updating.

**Comment by antedebaas** [comment]
apparently there was a bug in de installservice.sh it should be fixed in v1.5.0

**Comment by devkzidane** [comment]
Awesome, I've got working.

1- Is it okay to setup a cron to periodically do a `git pull` for updates?
2- I don't have to add domains, right? it will read all mail from the imap account and add domains manually?

**Comment by antedebaas** [comment]
1: I would not run pull directly as the main branch can contain unfinished code. I would run the update script then as that updates releases
2: it does that automatically, yes

**Comment by devkzidane** [comment]
That works. Thanks for all, closing for now.
