### ISSUE TITLE
Feature Request: make reports & domains deleteable in GUI

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#31]
Hi Ante,

I would like to ask another feature which I guess could be really useful:

**Make single reports & domains deleteable in the GUI**

_Motivation_: 
Sometimes it happens that a report (which my server sent out) returned undeliverable, because of mailbox full, wrong DMARC DNS record etc. If the returned mail contains still the xml report file, this undeliverable mail will also be imported into the database which confuses the overview, as I only want to see the reports I have received from others and not the ones I have sent myself. 

So far, I have always deleted the entire database and re-imported all reports already received. However, it would be much easier if you could simply delete the "wrong" reports in the GUI with a simple click.

As I have no programming experience, I can't say whether this change would be a big effort, but if you have the time and motivation, you could perhaps have a look at it one day. 

As always, many thanks for your effort.

Cheers...

**Comment by antedebaas** [comment]
Hi @bundyland 
Seems like you made it a bit hard on yourself.
But yes the database is designed to have entries linked for consistency. If you want to delete a domain you need to delete all reports (smtp-tls and dmarc, with all their entries in their sub-tables) first. A bit of a hassle.
I have planned on adding a delete option on both report and domain level. I just haven’t had the time yet.
I’ll leave this open as a reminder :)

**Comment by bundyland** [comment]
That sounds great. Thanks a lot.

**Comment by antedebaas** [comment]
this is now implemented in v1.6.0
https://github.com/antedebaas/DMARC-SMTPTLS-Reports/releases/tag/v1.6.0

**Comment by bundyland** [comment]
Great job, Ante. I will update tonight.
Thank you very much.
