### ISSUE TITLE
Feature Request: Check schedule option

### ISSUE THREAD

**Issue by kimdre** [antedebaas/DMARC-Reports#32]
Am I correct that the check schedule at the moment is set to daily with this systemd timer?

https://github.com/antedebaas/DMARC-SMTPTLS-Reports/blob/c5ccf38254b01c3ee4bd5af0d0323b13c53392e8/systemd/dmarcmailcheck.timer#L5

Could you maybe add an env var that lets you set this schedule to something else if needed?

**Comment by antedebaas** [comment]
as stated in the merge request; the proposed solution does not work in all cases.
i will however be implementing a more flexible way of running the task.

**Comment by antedebaas** [comment]
implemented in release 1.7.0

todo: documentation:
options are: monthly, weekly, daily, hourly, 15min or custom cron input (e.g. */5 * * * *)

**Comment by antedebaas** [comment]
documentation updated
