### ISSUE TITLE
Bug: Pagination on Domain Overview leads to Logs Page

### ISSUE THREAD

**Issue by kimdre** [antedebaas/DMARC-Reports#35]
When I try to use the pagination arrow on `/domains` to the next page, the link leads me to `/logs`. For example the next page button leads to `/logs?page=2&perpage=17`

**Comment by antedebaas** [comment]
thank you :)

**Comment by kimdre** [comment]
Will you create a patch release for this?

**Comment by antedebaas** [comment]
Tomorrow :)
