### ISSUE TITLE
Feature Request: possibility to deactivate the registration

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#38]
Hi Ante,

would it be possible to deactivate the register function through the envirement options? For example if someone only needs one single admin account and don't want to allow further registrations?

Motiv:
Especially if someone runs the parser on a public server (like I do), it could be useful for security to avoid any unwanted registrations.

As a workaround I have disallowed the register link through my reverse proxy, but it would be much easier if we could simply deactivate the registration directly in the docker compose file.

Many thanks.

Best...

**Comment by antedebaas** [comment]
I’ll have a look at what the best way of implementing this is for this project.

Just as a side note; users can only see the domains they have assigned (and add new once’s). Only admins can see everything. 
as for adding new domain; if they don’t know what email address is used it’s pointless for them.

**Comment by antedebaas** [comment]
implemented in release 1.7.0
