### ISSUE TITLE
This is not working on for me

### ISSUE THREAD

**Issue by Blason** [antedebaas/DMARC-Reports#39]
Hi,

I tried running this on ubuntu 22.04 and it gave me lot of dependencies and it could not run. Then I tried with Docker and it gave to me weird error which forced to comment the name and containers stated working fine. I then pointed to imap.gmail.com and not a single mail was downloaded nothing appeared on dashboard.

Is this something you can help me with?

**Comment by Blason** [comment]
docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by Blason** [comment]
And thats an issue when update.sh ran

  Problem 1
    - Root composer.json requires php >=8.2 but your php version (8.1.2) does not satisfy that requirement.
  Problem 2
    - php-imap/php-imap is locked to version 5.0.1 and an update of this package was not requested.
    - php-imap/php-imap 5.0.1 requires ext-imap * -> it is missing from your system. Install or enable PHP's imap extension.
  Problem 3
    - secit-pl/imap-bundle is locked to version 3.0.0 and an update of this package was not requested.
    - secit-pl/imap-bundle 3.0.0 requires ext-imap * -> it is missing from your system. Install or enable PHP's imap extension.
  Problem 4
    - symfony/cache is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/cache v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 5
    - symfony/clock is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/clock v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 6
    - symfony/config is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/config v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 7
    - symfony/console is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/console v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 8
    - symfony/dependency-injection is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/dependency-injection v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 9
    - symfony/doctrine-bridge is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/doctrine-bridge v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 10
    - symfony/dotenv is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/dotenv v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 11
    - symfony/error-handler is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/error-handler v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 12
    - symfony/event-dispatcher is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/event-dispatcher v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 13
    - symfony/filesystem is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/filesystem v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 14
    - symfony/finder is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/finder v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 15
    - symfony/form is locked to version v7.0.1 and an update of this package was not requested.
    - symfony/form v7.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 16
    - symfony/framework-bundle is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/framework-bundle v7.0.2 requires ext-xml * -> it is missing from your system. Install or enable PHP's xml extension.
  Problem 17
    - symfony/http-foundation is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/http-foundation v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 18
    - symfony/http-kernel is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/http-kernel v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 19
    - symfony/mailer is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/mailer v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 20
    - symfony/mime is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/mime v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 21
    - symfony/options-resolver is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/options-resolver v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 22
    - symfony/password-hasher is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/password-hasher v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 23
    - symfony/property-access is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/property-access v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 24
    - symfony/property-info is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/property-info v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 25
    - symfony/routing is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/routing v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 26
    - symfony/runtime is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/runtime v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 27
    - symfony/security-bundle is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/security-bundle v7.0.2 requires ext-xml * -> it is missing from your system. Install or enable PHP's xml extension.
  Problem 28
    - symfony/security-core is locked to version v7.0.1 and an update of this package was not requested.
    - symfony/security-core v7.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 29
    - symfony/security-csrf is locked to version v7.0.1 and an update of this package was not requested.
    - symfony/security-csrf v7.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 30
    - symfony/security-http is locked to version v7.0.1 and an update of this package was not requested.
    - symfony/security-http v7.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 31
    - symfony/stopwatch is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/stopwatch v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 32
    - symfony/string is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/string v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 33
    - symfony/translation is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/translation v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 34
    - symfony/twig-bridge is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/twig-bridge v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 35
    - symfony/twig-bundle is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/twig-bundle v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 36
    - symfony/validator is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/validator v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 37
    - symfony/var-dumper is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/var-dumper v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 38
    - symfony/var-exporter is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/var-exporter v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 39
    - symfony/yaml is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/yaml v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 40
    - masterminds/html5 is locked to version 2.8.1 and an update of this package was not requested.
    - masterminds/html5 2.8.1 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 41
    - phar-io/manifest is locked to version 2.0.3 and an update of this package was not requested.
    - phar-io/manifest 2.0.3 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 42
    - phpunit/php-code-coverage is locked to version 9.2.30 and an update of this package was not requested.
    - phpunit/php-code-coverage 9.2.30 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 43
    - phpunit/phpunit is locked to version 9.6.16 and an update of this package was not requested.
    - phpunit/phpunit 9.6.16 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 44
    - symfony/browser-kit is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/browser-kit v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 45
    - symfony/css-selector is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/css-selector v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 46
    - symfony/dom-crawler is locked to version v7.0.0 and an update of this package was not requested.
    - symfony/dom-crawler v7.0.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 47
    - symfony/process is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/process v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 48
    - symfony/web-profiler-bundle is locked to version v7.0.2 and an update of this package was not requested.
    - symfony/web-profiler-bundle v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 49
    - theseer/tokenizer is locked to version 1.2.2 and an update of this package was not requested.
    - theseer/tokenizer 1.2.2 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 50
    - symfony/cache v7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
    - doctrine/doctrine-bundle 2.11.1 requires symfony/cache ^5.4 || ^6.0 || ^7.0 -> satisfiable by symfony/cache[v7.0.2].
    - doctrine/doctrine-bundle is locked to version 2.11.1 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-intl.ini
    - /etc/php/8.1/cli/conf.d/20-mbstring.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-imap --ignore-platform-req=ext-imap --ignore-platform-req=ext-xml --ignore-platform-req=ext-xml --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom` to temporarily ignore these required extensions.
clear cache
PHP Fatal error:  Uncaught LogicException: Symfony Runtime is missing. Try running "composer require symfony/runtime". in /opt/DMARC-SMTPTLS-Reports/bin/console:8
Stack trace:
#0 {main}
  thrown in /opt/DMARC-SMTPTLS-Reports/bin/console on line 8
run migrations
PHP Fatal error:  Uncaught LogicException: Symfony Runtime is missing. Try running "composer require symfony/runtime". in /opt/DMARC-SMTPTLS-Reports/bin/console:8
Stack trace:
#0 {main}
  thrown in /opt/DMARC-SMTPTLS-Reports/bin/console on line 8
run upgrade script
done
install assets
PHP Fatal error:  Uncaught LogicException: Symfony Runtime is missing. Try running "composer require symfony/runtime". in /opt/DMARC-SMTPTLS-Reports/bin/console:8
Stack trace:
#0 {main}

**Comment by Blason** [comment]
Ok - now correct php8.2 and ran it again - and I am facing below issues,

M       docker-compose.yml
M       update.sh
HEAD is now at 341b114 update update.sh
Install composer dependencies
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:48
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:56
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]?
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:884
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 109 installs, 0 updates, 0 removals
  - Downloading symfony/flex (v2.4.3)
  - Downloading symfony/runtime (v7.0.0)
  - Downloading symfony/deprecation-contracts (v3.4.0)
  - Downloading symfony/routing (v7.0.2)
  - Downloading symfony/polyfill-mbstring (v1.28.0)
  - Downloading symfony/polyfill-php83 (v1.28.0)
  - Downloading symfony/http-foundation (v7.0.0)
  - Downloading psr/event-dispatcher (1.0.0)
  - Downloading symfony/event-dispatcher-contracts (v3.4.0)
  - Downloading symfony/event-dispatcher (v7.0.2)
  - Downloading symfony/var-dumper (v7.0.2)
  - Downloading psr/log (3.0.0)
  - Downloading symfony/error-handler (v7.0.0)
  - Downloading symfony/http-kernel (v7.0.2)
  - Downloading symfony/finder (v7.0.0)
  - Downloading symfony/filesystem (v7.0.0)
  - Downloading symfony/var-exporter (v7.0.2)
  - Downloading psr/container (2.0.2)
  - Downloading symfony/service-contracts (v3.4.1)
  - Downloading symfony/dependency-injection (v7.0.2)
  - Downloading symfony/config (v7.0.0)
  - Downloading psr/cache (3.0.0)
  - Downloading symfony/cache-contracts (v3.4.0)
  - Downloading symfony/cache (v7.0.2)
  - Downloading symfony/framework-bundle (v7.0.2)
  - Downloading symfony/stopwatch (v7.0.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.28.0)
  - Downloading symfony/polyfill-intl-grapheme (v1.28.0)
  - Downloading symfony/string (v7.0.2)
  - Downloading symfony/console (v7.0.2)
  - Downloading doctrine/event-manager (2.0.0)
  - Downloading doctrine/deprecations (1.1.2)
  - Downloading doctrine/cache (2.2.0)
  - Downloading doctrine/dbal (3.7.3)
  - Downloading doctrine/migrations (3.7.2)
  - Downloading doctrine/persistence (3.2.0)
  - Downloading symfony/doctrine-bridge (v7.0.2)
  - Downloading doctrine/sql-formatter (1.1.3)
  - Downloading doctrine/doctrine-bundle (2.11.1)
  - Downloading doctrine/doctrine-migrations-bundle (3.3.0)
  - Downloading doctrine/lexer (2.1.0)
  - Downloading doctrine/instantiator (2.0.0)
  - Downloading doctrine/inflector (2.0.9)
  - Downloading doctrine/common (3.4.3)
  - Downloading doctrine/collections (2.1.4)
  - Downloading doctrine/orm (2.17.3)
  - Downloading sebastian/version (3.0.2)
  - Downloading sebastian/type (3.2.1)
  - Downloading sebastian/resource-operations (3.0.3)
  - Downloading sebastian/recursion-context (4.0.5)
  - Downloading sebastian/object-reflector (2.0.4)
  - Downloading sebastian/object-enumerator (4.0.4)
  - Downloading sebastian/global-state (5.0.6)
  - Downloading sebastian/exporter (4.0.5)
  - Downloading sebastian/environment (5.1.5)
  - Downloading sebastian/diff (4.0.5)
  - Downloading sebastian/comparator (4.0.8)
  - Downloading sebastian/code-unit (1.0.8)
  - Downloading sebastian/cli-parser (1.0.1)
  - Downloading phpunit/php-timer (5.0.3)
  - Downloading phpunit/php-text-template (2.0.4)
  - Downloading phpunit/php-invoker (3.1.1)
  - Downloading phpunit/php-file-iterator (3.0.6)
  - Downloading theseer/tokenizer (1.2.2)
  - Downloading nikic/php-parser (v4.18.0)
  - Downloading sebastian/lines-of-code (1.0.4)
  - Downloading sebastian/complexity (2.0.3)
  - Downloading sebastian/code-unit-reverse-lookup (2.0.3)
  - Downloading phpunit/php-code-coverage (9.2.30)
  - Downloading phar-io/version (3.2.1)
  - Downloading phar-io/manifest (2.0.3)
  - Downloading myclabs/deep-copy (1.11.1)
  - Downloading phpunit/phpunit (9.6.16)
  - Downloading psr/clock (1.0.0)
  - Downloading php-imap/php-imap (5.0.1)
  - Downloading secit-pl/imap-bundle (3.0.0)
  - Downloading symfony/apache-pack (v1.0.1)
  - Downloading masterminds/html5 (2.8.1)
  - Downloading symfony/dom-crawler (v7.0.0)
  - Downloading symfony/browser-kit (v7.0.0)
  - Downloading symfony/css-selector (v7.0.0)
  - Downloading symfony/dotenv (v7.0.2)
  - Downloading symfony/property-info (v7.0.0)
  - Downloading symfony/property-access (v7.0.0)
  - Downloading symfony/polyfill-intl-icu (v1.28.0)
  - Downloading symfony/options-resolver (v7.0.0)
  - Downloading symfony/form (v7.0.1)
  - Downloading symfony/polyfill-intl-idn (v1.28.0)
  - Downloading symfony/mime (v7.0.0)
  - Downloading egulias/email-validator (4.0.2)
  - Downloading symfony/mailer (v7.0.2)
  - Downloading symfony/process (v7.0.2)
  - Downloading symfony/maker-bundle (v1.52.0)
  - Downloading symfony/phpunit-bridge (v7.0.2)
  - Downloading symfony/password-hasher (v7.0.0)
  - Downloading symfony/security-core (v7.0.1)
  - Downloading symfony/security-http (v7.0.1)
  - Downloading symfony/security-csrf (v7.0.1)
  - Downloading symfony/clock (v7.0.2)
  - Downloading symfony/security-bundle (v7.0.2)
  - Downloading symfony/translation-contracts (v3.4.1)
  - Downloading symfony/translation (v7.0.2)
  - Downloading twig/twig (v3.8.0)
  - Downloading symfony/twig-bridge (v7.0.2)
  - Downloading symfony/validator (v7.0.2)
  - Downloading symfony/twig-bundle (v7.0.0)
  - Downloading symfony/web-profiler-bundle (v7.0.2)
  - Downloading symfony/yaml (v7.0.0)
  - Downloading symfonycasts/verify-email-bundle (v1.16.1)
  - Installing symfony/flex (v2.4.3): Extracting archive
  - Installing symfony/runtime (v7.0.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.4.0): Extracting archive
  - Installing symfony/routing (v7.0.2): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.28.0): Extracting archive
  - Installing symfony/polyfill-php83 (v1.28.0): Extracting archive
  - Installing symfony/http-foundation (v7.0.0): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.4.0): Extracting archive
  - Installing symfony/event-dispatcher (v7.0.2): Extracting archive
  - Installing symfony/var-dumper (v7.0.2): Extracting archive
  - Installing psr/log (3.0.0): Extracting archive
  - Installing symfony/error-handler (v7.0.0): Extracting archive
  - Installing symfony/http-kernel (v7.0.2): Extracting archive
  - Installing symfony/finder (v7.0.0): Extracting archive
  - Installing symfony/filesystem (v7.0.0): Extracting archive
  - Installing symfony/var-exporter (v7.0.2): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.4.1): Extracting archive
  - Installing symfony/dependency-injection (v7.0.2): Extracting archive
  - Installing symfony/config (v7.0.0): Extracting archive
  - Installing psr/cache (3.0.0): Extracting archive
  - Installing symfony/cache-contracts (v3.4.0): Extracting archive
  - Installing symfony/cache (v7.0.2): Extracting archive
  - Installing symfony/framework-bundle (v7.0.2): Extracting archive
  - Installing symfony/stopwatch (v7.0.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.28.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.28.0): Extracting archive
  - Installing symfony/string (v7.0.2): Extracting archive
  - Installing symfony/console (v7.0.2): Extracting archive
  - Installing doctrine/event-manager (2.0.0): Extracting archive
  - Installing doctrine/deprecations (1.1.2): Extracting archive
  - Installing doctrine/cache (2.2.0): Extracting archive
  - Installing doctrine/dbal (3.7.3): Extracting archive
  - Installing doctrine/migrations (3.7.2): Extracting archive
  - Installing doctrine/persistence (3.2.0): Extracting archive
  - Installing symfony/doctrine-bridge (v7.0.2): Extracting archive
  - Installing doctrine/sql-formatter (1.1.3): Extracting archive
  - Installing doctrine/doctrine-bundle (2.11.1): Extracting archive
  - Installing doctrine/doctrine-migrations-bundle (3.3.0): Extracting archive
  - Installing doctrine/lexer (2.1.0): Extracting archive
  - Installing doctrine/instantiator (2.0.0): Extracting archive
  - Installing doctrine/inflector (2.0.9): Extracting archive
  - Installing doctrine/common (3.4.3): Extracting archive
  - Installing doctrine/collections (2.1.4): Extracting archive
  - Installing doctrine/orm (2.17.3): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (3.2.1): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.5): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.6): Extracting archive
  - Installing sebastian/exporter (4.0.5): Extracting archive
  - Installing sebastian/environment (5.1.5): Extracting archive
  - Installing sebastian/diff (4.0.5): Extracting archive
  - Installing sebastian/comparator (4.0.8): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.2): Extracting archive
  - Installing nikic/php-parser (v4.18.0): Extracting archive
  - Installing sebastian/lines-of-code (1.0.4): Extracting archive
  - Installing sebastian/complexity (2.0.3): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.30): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.1): Extracting archive
  - Installing phpunit/phpunit (9.6.16): Extracting archive
  - Installing psr/clock (1.0.0): Extracting archive
  - Installing php-imap/php-imap (5.0.1): Extracting archive
  - Installing secit-pl/imap-bundle (3.0.0): Extracting archive
  - Installing symfony/apache-pack (v1.0.1): Extracting archive
  - Installing masterminds/html5 (2.8.1): Extracting archive
  - Installing symfony/dom-crawler (v7.0.0): Extracting archive
  - Installing symfony/browser-kit (v7.0.0): Extracting archive
  - Installing symfony/css-selector (v7.0.0): Extracting archive
  - Installing symfony/dotenv (v7.0.2): Extracting archive
  - Installing symfony/property-info (v7.0.0): Extracting archive
  - Installing symfony/property-access (v7.0.0): Extracting archive
  - Installing symfony/polyfill-intl-icu (v1.28.0): Extracting archive
  - Installing symfony/options-resolver (v7.0.0): Extracting archive
  - Installing symfony/form (v7.0.1): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.28.0): Extracting archive
  - Installing symfony/mime (v7.0.0): Extracting archive
  - Installing egulias/email-validator (4.0.2): Extracting archive
  - Installing symfony/mailer (v7.0.2): Extracting archive
  - Installing symfony/process (v7.0.2): Extracting archive
  - Installing symfony/maker-bundle (v1.52.0): Extracting archive
  - Installing symfony/phpunit-bridge (v7.0.2): Extracting archive
  - Installing symfony/password-hasher (v7.0.0): Extracting archive
  - Installing symfony/security-core (v7.0.1): Extracting archive
  - Installing symfony/security-http (v7.0.1): Extracting archive
  - Installing symfony/security-csrf (v7.0.1): Extracting archive
  - Installing symfony/clock (v7.0.2): Extracting archive
  - Installing symfony/security-bundle (v7.0.2): Extracting archive
  - Installing symfony/translation-contracts (v3.4.1): Extracting archive
  - Installing symfony/translation (v7.0.2): Extracting archive
  - Installing twig/twig (v3.8.0): Extracting archive
  - Installing symfony/twig-bridge (v7.0.2): Extracting archive
  - Installing symfony/validator (v7.0.2): Extracting archive
  - Installing symfony/twig-bundle (v7.0.0): Extracting archive
  - Installing symfony/web-profiler-bundle (v7.0.2): Extracting archive
  - Installing symfony/yaml (v7.0.0): Extracting archive
  - Installing symfonycasts/verify-email-bundle (v1.16.1): Extracting archive
Generating autoload files
93 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]

clear cache

 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


run migrations
[critical] Error thrown while running command "doctrine:migrations:migrate --no-interaction --query-time". Message: "An exception occurred in the driver: could not find driver"

In ExceptionConverter.php line 83:

  An exception occurred in the driver: could not find driver


In Exception.php line 28:

  could not find driver


In Driver.php line 43:

  could not find driver


doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]

run upgrade script
done
install assets

 Installing assets as hard copies.


 [OK] No assets were provided by any bundle.


warmup cache

 // Warming up the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.

**Comment by antedebaas** [comment]
1. this project requires php 8.2 or higher.
2. use "docker compose up" which works fine
3. you are missing the php-pdo driver for what i guess is sqlite as this is the default before you have run the config.

**Comment by Blason** [comment]
Was that mentioned or I misread that! Thanks for heads up let me give a try

**Comment by Blason** [comment]
Am I having any issues - apt-get install php8.2-pdo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'php8.2-common' instead of 'php8.2-pdo'
php8.2-common is already the newest version (8.2.15-1+ubuntu22.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

**Comment by antedebaas** [comment]
I think you need php-mysql on Ubuntu. 
the package names I listed are the generic onces

**Comment by Blason** [comment]
docker is working fine so I'll choose that path
