### ISSUE TITLE
BUG (cosmetic issue): TLS-RPT with TLSA/DANE results looks strange

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#41]
Hi Ante,

if you receive a TLS-RPT with DANE/TLSA results, it will look like this in the report overview:

![2](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/f2e7d883-2c10-4b38-ab3f-5cb1a75ba393)

The full report looks like this:

![1](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/b1da5526-40d5-490a-9707-3d5b9927e30d)

It simply looks like there is no nice button available for TLSA in the results column and that's maybe why there is just a red dot. 
Is this something you could easily fix? Of course not urgent at all. It's only for the perfectionists. ;-)

Thank you lots.

Regards...

**Comment by antedebaas** [comment]
I could not test it myself. Can you provide an example (anonymized) report for me?

**Comment by bundyland** [comment]
Sure:

[microsoft.com!domain.de!1708905600!1708991999!133535354203065975.json](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/files/14439908/microsoft.com.domain.de.1708905600.1708991999.133535354203065975.json)

**Comment by antedebaas** [comment]
thanks im looking into this:
TSLA is not implemented at the moment so that it sort of works was by luck.
ill start on implementing it.

notes to self:
https://datatracker.ietf.org/doc/rfc8460/ -> 4.5.  Policy Samples

**Comment by antedebaas** [comment]
implemented in release 1.7.0

**Comment by bundyland** [comment]
Great job, Ante! 
Thank you very much.
