### ISSUE TITLE
Sqlite upgrade error to v1.8.0

### ISSUE THREAD

**Issue by mverboom** [antedebaas/DMARC-Reports#42]
Hi,

When upgrading to 1.8.0 with an sqlite database, the table upgrade (migrations/sqlite/Version20240304200718.php) shows an error.
The query:

`ALTER TABLE logs ADD COLUMN success BOOLEAN NOT NULL;`

gives an error because sqlite expects a default value it seems for the not null column. I changed it to:

`ALTER TABLE logs ADD COLUMN success BOOLEAN NOT NULL default false;`

and it seems to be happy.

Regards,

Mark

**Comment by antedebaas** [comment]
Thanks for letting me know. I’ll update it as soon as I have the time.
I would suggest to set the default to true tho

**Comment by antedebaas** [comment]
fixed in v1.8.1
