### ISSUE TITLE
Question and/or Feature Request: purge logs (automatically or manually)

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#43]
Hi Ante,

is there any possibility to purge the logs easily?

If not, do you think it would be possible to create an automatism to purge the logs (for example) every 30 days? 
Or at least a button which allows purging the logs through the GUI?

Motiv:
I don't really see the requirement to keep these logs for an unlimited period of time. To prevent the database from becoming unnecessarily bloated, I prefer to keep these logs just for a limited time.

As always, thank you very much for the great work.

Best regards....

**Comment by antedebaas** [comment]
i can add a cleanlogs command you could run.

**Comment by bundyland** [comment]
That sounds wonderful. Thanks a lot.

**Comment by antedebaas** [comment]
implemented in 1.9.0

**Comment by bundyland** [comment]
Thank you very much, Ante. 

Could you please let me know which exact command I have to run under Docker to get the logs purged?

**Comment by bundyland** [comment]
No worries. I've found it. It should be:

`docker exec -t dmarc-web-1 php /var/www/html/bin/console app:clearlogs`

... and it works great. Thanks once again.
