### ISSUE TITLE
Bug that prevents mail deletion

### ISSUE THREAD

**Issue by wvogel** [antedebaas/DMARC-Reports#47]
There is an error hat will cause an http error 500 when setting `DELETE_PROCESSED_MAILS=true` in `.env.local`.

Line `92` of `src/Command/GetReportsFromMailboxCommand.php` reads:
`$mailbox->deleteMail($mailId);`

It has to be:
`$mailbox->deleteMail($mailid);`

I sent a pull request...

**Comment by antedebaas** [comment]
Thanks!

**Comment by wvogel** [comment]
Thanks for this wonderful project, Ante! :)
