### ISSUE TITLE
Installation guide unclear

### ISSUE THREAD

**Issue by ghost** [antedebaas/DMARC-Reports#52]
The "Setup is not pretty easy" statement is pretty exaggerated.
After installing the prerequisites it's unclear what steps need to be taken and what to configure where.
After cloning the repository and pointing the Apache2 configuration to the _public_ folder in the best case one gets a blank page when accessing localhost in the browser. Next, a "Not found" error is returned when accessing "localhost/setup".

Please either provide step by step instructions or a real install script one can use which takes care of installing all dependencies from trusted sources and takes over the configuration.
Other than that it's impossible non-professionals to make use of your good prework.

**Comment by antedebaas** [comment]
seems to me that your apache install isnt reading the .htaccess file in de public directory
