### ISSUE TITLE
Feature Request: Multi tenant - Or is that feature already there?

### ISSUE THREAD

**Issue by Blason** [antedebaas/DMARC-Reports#53]
Hi there,

Wondering if we can configure multi tenant using existing docker? Or how do I configure multiple domains with multiple logins? so that user from one domain should not have access to reports from other domain.

Is that possible?

**Comment by antedebaas** [comment]
Currently only users have access to their granted domains. Admins can see everything

**Comment by Blason** [comment]
Need to see that does that mean if I have
userx assigned to domainx
usery assigned to domainy

userx can not see content of domainy and vice-versa?

**Comment by antedebaas** [comment]
Yes
