### ISSUE TITLE
Feature request: Allow for smaller screen sizes

### ISSUE THREAD

**Issue by wvogel** [antedebaas/DMARC-Reports#55]
Maybe just a quick finger exercise for someone who is experienced with bootstrap:
It would be wonderful if the layout were a bit more compact, so that nothing wraps in the left column and in the two wide columns of the dashboard each report fit in one line without wrapping.

**Comment by antedebaas** [comment]
agreed. ill look into it

**Comment by jensb** [comment]
I have started to work on this. For now, I've removed the icon sidebar (icons at the top), reduced padding in a dozen places, and if there's just one single table in the screen, removed the "card" padding around it. Also, for DMARC reports lists, I've made some columns' display depend on the screen size.

I will create some screenshots shortly to discuss.

**Comment by antedebaas** [comment]
Please make a pull request at the end so we can merge the changes

**Comment by jensb** [comment]
Will do. Is there a way to check out the app with some dummy data to experiment with, and does Symfony offer a local small builtin HTTP server to avoid having to set up Apache? Right now I'm doing the changes live on my production machine ... :-)

**Comment by antedebaas** [comment]
Yes there is.  But you’ll need the symfony cli and a working php installation.

https://symfony.com/doc/current/setup/symfony_server.html

**Comment by jensb** [comment]
OK, that's great.
Can you quickly give me a SQL to insert 1-2 dummy TLS reports so I can also fine tune the TLS index display?

Here's a sneak preview. :-)
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/44540/493d2a28-5fcc-4bc0-8c32-5f976a04e6e2)

**Comment by antedebaas** [comment]
Great start.
I am however not a big fan of the buttons in the title bar. There is a menu for a reason.
Could you also add a bit more spacing. I know the current design uses a lot of space but I think the sweet spot is between the current design and this design.

as for sample data. I’m currently not home so I can’t provide any at the moment

**Comment by antedebaas** [comment]
Also. Maybe you can add the actions to a dropdown menu. Also for future sake.  If any feature get added it’s already there.
If you click on the table row it could open te report and have a dropdown for all other actions.

**Comment by jensb** [comment]
Was just typing ... :-) the top icons are for larger screens. As soon as the menu is there they will vanish. On mobile devices horizontal space is valuable, so I removed the sidebar menu. I could not get this to work properly (width adjustment, spacing, wrapping) anyway and there is ample space at the top.

Updated screenshot coming soon.

**Comment by antedebaas** [comment]
The langer screens have a sidebar for menu so they don’t need it.
I prefer not to have those buttons as I want a clean design.

**Comment by jensb** [comment]
Yes, a clean design was also my goal. Also, most efficient screen usage. Thus I removed the sidebar menu :-)
It's probably a matter of taste. Let's see where we end up.

Mobile:
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/44540/fb27e5f6-56aa-49e9-9667-e6f659ea2530)

![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/44540/f4551371-7870-4c53-a5cc-ca1356ea76dc)

Medium (no menu, more columns):
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/44540/78b2bf7b-efd0-479b-bece-0dbea86df50a)

Large and XL (even more columns, note the date formatting, Report IDs are shortened but fully available via tooltip)
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/44540/9455ffad-9adc-4e27-8407-81172ce59616)

**Comment by jensb** [comment]
I don't fully like the button alignment and the table design yet, but that's the general idea.

**Comment by antedebaas** [comment]
Don’t remove the sidebar menu and keep the title bar for just the title.

**Comment by jensb** [comment]
I didn't remove it, I hid it because it wasn't working properly.

I will try to show it e.g. for xl and xxl screens (width >1200px).
For anything less - especially mobile - a fixed sidebar column does not make sense IMHO.

**Comment by antedebaas** [comment]
I've implemented a version that keeps the current layout the same and hides non-primary columns on smaller devices.
any future changes can be made via a new issue/pr

**Comment by jensb** [comment]
Why did you not wait for my pull request?
I spent quite some time today setting up a local dev environment for PHP just for this project (don't usually do PHP) and creating a pull request against master. Now I have to merge again.
That's a little discouraging regarding future collaboration. :-(

**Comment by antedebaas** [comment]
Hi @jensb i wanted to try a few things myself but didn't mean to discourage you.
youre still welcome to submit your pr.

**Comment by jensb** [comment]
OK. No worries. Trying to merge your changes now.
We do disagree on a few things like which columns are "important" in a table but IMHO these are side issues.
