### ISSUE TITLE
Latest logs empty

### ISSUE THREAD

**Issue by paixaocbr** [antedebaas/DMARC-Reports#56]
Hi,

The latest log windows is empty:
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/73401399/379ab472-7700-464b-832c-f6e9c2b512a0)

The web container have this error:
NOTICE: PHP message: [critical] Error thrown while running command "app:getreportsfrommailbox". Message: "Cannot create the attachments directory "/var/www/html/var/imap/attachments""
2024/03/13 14:07:12 [error] 17#17: *19 FastCGI sent in stderr: "PHP message: [critical] Error thrown while running command "app:getreportsfrommailbox". Message: "Cannot create the attachments directory "/var/www/html/var/imap/attachments""" while reading response header from upstream, client: 10.0.0.4, server: _, request: "GET /reports/checkmailnow HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "dmarcsrv.example.com", referrer: "https://dmarcsrv.example.com/logs"

Any help?

Thanks,
Pedro Paixão

**Comment by sn3ak** [comment]
It looks like you might be using docker?

If so, try following [this](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/issues/51#issuecomment-1986459923) comment and see if it works, or if you get another error.

**Comment by antedebaas** [comment]
there was a bug when using the check mail now button.
this has been fixed in 1.8.2

**Comment by paixaocbr** [comment]
> It looks like you might be using docker?
> 
> If so, try following [this](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/issues/51#issuecomment-1986459923) comment and see if it works, or if you get another error.

Hello,

Got this error:
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/73401399/0ddf5125-38b6-4928-86c2-5997b35c5030)

**Comment by antedebaas** [comment]
ugh!
forgot to check for null value.
should be fixed in 1.9.1
@paixaocbr
