### ISSUE TITLE
Feature Request: Microsoft 365 OAuth

### ISSUE THREAD

**Issue by wvogel** [antedebaas/DMARC-Reports#57]
Microsoft have removed the login/password authentication for IMAP access and require OAuth. Without, an inbox cannot be accessed.

**Comment by antedebaas** [comment]
unfortunately this is not supported by php-imap yet:
see: https://github.com/barbushin/php-imap/issues/411

**Comment by KGBist2000** [comment]
> Microsoft have removed the login/password authentication for IMAP access and require OAuth. Without, an inbox cannot be accessed.

On Google Workspace it is possible to create APP-Password to access e.g. the emals. Is on M365 same possible ?

**Comment by antedebaas** [comment]
Since discussions have halted and I don’t see this working in the foreseeable future I’m closing this
