### ISSUE TITLE
BUG: TLSRP policy version and mode empty

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#58]
Hi Ante,

since one of the latest updates there seems to be a problem with the TLS reports as you can seen here:

![Screenshot 2024-03-22 125443](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/b07e6f29-ed4e-434f-a014-1c03528cb1ff)

The **policy version** and the **policy mode** are indeed available in the report as you can verify here:

[google.com!domain.de!1710979200!1711065599!001.json](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/files/14722136/google.com.domain.de.1710979200.1711065599.001.json)

If you find some time, could you please have a look?

Thank you very much. Have a great weekend.

**Comment by antedebaas** [comment]
I’ll have a look at it

**Comment by antedebaas** [comment]
this is now fixed on the main branch
