### ISSUE TITLE
Feature Request:  Mark reports as read/unread

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#60]
Hi Ante,

I would kindly request another feature which could be useful:

**Mark (all) reports as read/unread**

Motivation:
due to technical problems it happens to me sometimes that I need to delete the database and to re-import all old reports. In this case I need to click every single report to mark them as read. It would be much easier if I could mark them all as read with just a single click as you can do similarly with emails.

As always, thank you very much!

**Comment by antedebaas** [comment]
I would really like to know what you do that requires you to re import all emails.
The project itself doesn’t do anything that requires you to do so.

**Comment by bundyland** [comment]
This happened to me twice, because one day the database returned error 500 and I wasn't able to do anything except deleting all data and to start from scratch. At this point a "mark them all as read" button would have been helpful.  However, if this also possible with a simple `docker exec` command, it would be kind if you could tell me the exact command to enter.
Thank you.

**Comment by antedebaas** [comment]
Again. I’d be more interested in why errors happen.  Reimports are a thing you do when it went wrong. I’d rather fix it from going wrong in the first place
