### ISSUE TITLE
envelope_to, envelope_from and header_from all empty in DKIM report

### ISSUE THREAD

**Issue by gboor** [antedebaas/DMARC-Reports#61]
I started using this tool a few days ago and have gathered a decent number of reports. When digging into them, I noticed that in the DKIM reports, the Envelope to, Envelope from and Header from fields are all empty.

I checked the database as well and those fields are all set to NULL, so it seems to be an issue with the parsing?

I can dig into this a bit more if needed, but maybe someone knows what is going on here. All the other info (IP, whether or not it passed, etc.) is all there.

**Comment by antedebaas** [comment]
thank you for noticing!
i have confirmed that they no longer seem to be paced.

**Comment by antedebaas** [comment]
could you check if it work now (use the main branch for this one)

**Comment by antedebaas** [comment]
a fix for this is currently in the main branch

**Comment by gboor** [comment]
Nice, thanks for the quick follow-up :)

Does this also mean there's a new :latest docker image?

**Comment by antedebaas** [comment]
there is now yes :)

**Comment by gboor** [comment]
Just upgraded and it's indeed fixed now! Thanks for the quick follow-up!
