### ISSUE TITLE
Feature Request: Manual Import/Upload?

### ISSUE THREAD

**Issue by ocdtrekkie** [antedebaas/DMARC-Reports#62]
I don't know how easy this would be to implement, but I'm very interested in aggregating and visualizing DMARC reports, but ideally without the tool in question actually talking to my mail server. Would it be possible to dump in a pile of DMARC reports, be they an MBOX or PST of them, a pile of EML email files, or a pile of just the XML report attachments, and have this collect and display them, without accessing the original mailbox?

**Comment by antedebaas** [comment]
i do plan to implement a reader for reading files locally.
the idea is that you can place the attachments directly into a folder which will be read when executing a command,
this will be able to run side-by-side with the check-email command.

**Comment by ocdtrekkie** [comment]
Awesome, that is great to hear!

I would really love a drop-to-upload in the web interface because I am looking at trying to run this in a container where file access is hard, but if that was implemented I am sure I could shoehorn something myself to get files into the directory on my own.

**Comment by antedebaas** [comment]
I think you’d misunderstand then.
I will not be creating a drag and drop web upload.
I will be creating a command that can read files from disk on the server side.
as for storage in a container this can be done easily as it’s build in by default

**Comment by ocdtrekkie** [comment]
I understood, I was just saying I'd probably have to implement something myself to get the files there.

**Comment by jdonnell15** [comment]
> I understood, I was just saying I'd probably have to implement something myself to get the files there.

I utilize power automate to pull my DMARC reports currently then  upload them to my linux machine where I can then import them in from a directory.  The tool I am currently using does not aggregate SMTP-TLS reports so I really would like to use this tool where I could import both of them and verify for all my domains.

**Comment by antedebaas** [comment]
I’ve decided I’m not going to implement this myself. You’re welcome to submit a pull request
