### ISSUE TITLE
Problems during installation/setup

### ISSUE THREAD

**Issue by mbsouth** [antedebaas/DMARC-Reports#75]
Thank you for this project, that's exactly what I was looking for. 
I'm not the biggest Synphony fan, but it´s ok. 
Unfortunately, I have/had problems during the installation. But first things first:

Server version: 10.4.28-MariaDB
Server charset: UTF-8 Unicode (utf8mb4) 
PHP version: 8.2.4 (XAMPP, Win10)

**.env.local**
1. phpmyadmin creates passwords that contains a slash symbol (/). A slash is not accepted in the constant **DATABASE_URL**. The password is stored as a plain text string (.env.local)
2. A similar scenario with passwords for the mail account: like an auto created password e.g. nx#22aZVyHM@U4. This time it's the @ symbol. @ is the separator between password and hostname in the **MAILER_DSN** constant.

Both cases caused a 500 server error. In the PHP error logfile, only one line was logged at a time:
`[Fri Apr 12 14:43:05.629402 2024] [php:notice] [pid 7044:tid 2032] [client 192.168.0.62:61668] [critical] Uncaught Exception: Malformed parameter "url".`

Maybe use base64 encrypted strings for password or syntax checking ...

Currently I'm stuck in a loop at the database schema updates:
```
    DoctrineMigrations\Version20240214121100
    DoctrineMigrations\Version20240302153203
    DoctrineMigrations\Version20240304200130
    DoctrineMigrations\Version20240317202800
```
SQL statements such as
`'ALTER TABLE dmarc_reports_users RENAME COLUMN dmarc_reports_id TO report_id'`
will not be executed. 

The statement should look like this for my environment:
```ALTER TABLE `dmarc_reports_users` CHANGE `dmarc_reports_id` `report_id`;```

What would be the minimum MariaDB version?
Do I have to do all entries manually or is there a hack?

Thank you for your effort!

**Comment by mbsouth** [comment]
I found an answer to my question: Maria-DB 10.5.2+
[https://mariadb.com/kb/en/alter-table/#rename-column](https://mariadb.com/kb/en/alter-table/#rename-column)

**Comment by antedebaas** [comment]
I'm also running it on mariadb 10.5 so thats not the problem.
have you specified the database type in a seperate value also?
as for the .env.local stuff, these are managed by symfony, there is nothing i can do about that.

**Comment by antedebaas** [comment]
Yes 10.5 would be the minimum.
As for the .env.local. I can’t change that since it’s a symfony thing.
But I’m sure I had an @ in the password field before.
