### ISSUE TITLE
Question: how to get correct timezone in the logs?

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#79]
Hi Ante,

it's just a cosmetic thing, but I like to know how to get the correct timezone in the logs?

I've already placed `TZ: Europe/Berlin` under environment in the docker-compose.yml, but there is always a 2 hour difference between the real local time and the time in the logs. Is there any way to get the correct information here? 

Thank you very much.

Regards

Joe

**Comment by antedebaas** [comment]
I’ll have to look into this

**Comment by antedebaas** [comment]
fixed in 1.12.0

**Comment by bundyland** [comment]
Awesome, Ante. Thank you very much!
