### ISSUE TITLE
BUG: wrong counting for SMTP-TLS Reports 

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#92]
Hi Ante,

it looks like the SMTP-TLS Reports are wrong counted. 

If I click on "Reports", I see this:

![Screenshot 2024-05-19 132005](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/1f453c87-4696-4a5c-88b5-2cc5cbc7c133)

But in reality I only have received 46 SMTP-TLS Reports:

![Screenshot 2024-05-19 132100](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/66ee6477-3b21-4535-bd21-d5efcee2b13d)

I have the impression that every SMTP report is somehow multiplied. Could that be?

Thanks as always.

Best

Jürgen

**Comment by antedebaas** [comment]
Definitely wrong.  fixed in 1.12.5

**Comment by bundyland** [comment]
You are a real champion. 👍
Thank you very much.
