### ISSUE TITLE
Maybe BUG: policy version / policy mode empty if type is TLSA

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#93]
Hi Ante,

maybe just a cosmetic thing, but I thought I report it anyway.

If the SMTP-TLS-Report contains the policy type **TLSA**, the fields for "String version" and "String mode" remain empty:

![Screenshot 2024-05-19 134001](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/44c4ce06-0625-496e-881a-12e7d731a748)

Here is a sample report:

[microsoft.com!mydomain.de!1715817600!1715903999!133604787689984837.json](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/files/15369218/microsoft.com.mydomain.de.1715817600.1715903999.133604787689984837.json)

Do you think you could put some "nicer" informations instead of red buttons? Red always makes me think of a serious bug although in this case there is no real problem. Probably just a cosmetic issue.

Thank you very much.

**Comment by antedebaas** [comment]
no these values should not display for an tlsa policy at all :)
fixed in 1.12.5

**Comment by bundyland** [comment]
You are a real champion. 👍
Thank you very much.
