### ISSUE TITLE
Feature-Request: Statistic Board

### ISSUE THREAD

**Issue by KGBist2000** [antedebaas/DMARC-Reports#95]
Can you please add a static board, with some overview:
- Table and Pi-charts for each domain
    - for each reporter
    - how many sfp, dkim, tls fail, passed, rejected, quarantine, count of reporter, top 10 reporter overview, total reports, total email per domain, total mails per reporter, etc. 
    - possibility to select the time for the fine tuning of the charts ( all, 1d, last week, last month or from date, till date)

For better understanding what i mean, pls. find following e.g. https://securityboulevard.com/2022/10/understanding-dmarc-reports/

**Comment by antedebaas** [comment]
@tobsowo also requested this a while ago.
this wont be developed soon but ill think about it

**Comment by antedebaas** [comment]
I’ve decided I’m not going to implement this myself. You’re welcome to submit a pull request
