### ISSUE TITLE
Installation not working as expected

### ISSUE THREAD

**Issue by WebCodePoet** [antedebaas/DMARC-Reports#96]
Got the Error: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'report_.users' doesn't exist.

**Comment by antedebaas** [comment]
it seems the database does not exist.
have you run the setup or run the migrations manually?
did you manually create a .env.local file by accident?

**Comment by WebCodePoet** [comment]
Hey, I fixed it by creating the tables by hand. The problem seems to be inside the installation routine on a server where Plesk is installed, but now it is working.

**Comment by antedebaas** [comment]
Could you elaborate a bit more?
Do you know why the tables could not be created?
you should never create the tables manually. these are system managed so this could create issues when updating later

**Comment by WebCodePoet** [comment]
Sorry, I can't say anything more about this. I have done the whole process from clone to install several times, it never worked, in the end I ignored the .sh scripts and run all by hand, after that, it starts working. Maybe it is a problem with the parsing of the sql syntax or something.

**Comment by stramag** [comment]
Hi Ante,

Please let me know the docker is necessary to use this solution.
I appreciate your help!

BR,
GáborS

**Comment by antedebaas** [comment]
@WebCodePoet can you tell me what database + version and php version your host is running?

**Comment by antedebaas** [comment]
> Hi Ante,
> 
> Please let me know the docker is necessary to use this solution. I appreciate your help!
> 
> BR, GáborS

are you having the same problem?

**Comment by WebCodePoet** [comment]
> @WebCodePoet can you tell me what database + version and php version your host is running?

PHP 8.3.7 with MariaDB 10.11.8

**Comment by stramag** [comment]
> > Hi Ante,
> > Please let me know the docker is necessary to use this solution. I appreciate your help!
> > BR, GáborS
> 
> are you having the same problem?

The app works for me, but the install instructions are unclear.
The docker and this command: docker compose up is necessary or not.

Thank you for your big help!

BR,
GáborS

**Comment by stramag** [comment]
> > > Hi Ante,
> > > Please let me know the docker is necessary to use this solution. I appreciate your help!
> > > BR, GáborS
> > 
> > 
> > are you having the same problem?
> 
> The app works for me, but the install instructions are unclear. The docker and this command: docker compose up is necessary or not.
> 
> Thank you for your big help!
> 
> BR, GáborS

Hi Ante,

Please can you answer my question?

Thank you for your help!

BR,
GáborS

**Comment by webdeck** [comment]
FYI, I installed this (non-docker) and got the same error in setup.  I then ran update.sh again, and now that there was an .env.local file created by setup, it could connect to the database to create the schema.  This was not clear from the documentation.

**Comment by antedebaas** [comment]
> > > Hi Ante,
> > > Please let me know the docker is necessary to use this solution. I appreciate your help!
> > > BR, GáborS
> > 
> > 
> > are you having the same problem?
> 
> The app works for me, but the install instructions are unclear. The docker and this command: docker compose up is necessary or not.
> 
> Thank you for your big help!
> 
> BR, GáborS

you need to fill in the variables in the docker compose file. but other than that it should just work

**Comment by antedebaas** [comment]
> FYI, I installed this (non-docker) and got the same error in setup. I then ran update.sh again, and now that there was an .env.local file created by setup, it could connect to the database to create the schema. This was not clear from the documentation.

I'll have a look at the initial setup flow.

**Comment by deanfourie1** [comment]
I can confirm that the docker compose does not work

**Comment by antedebaas** [comment]
> I can confirm that the docker compose does not work

Could you please be more specific?
What errors do you get?

**Comment by antedebaas** [comment]
there was a bug in the setup script preventing the normal setup flow.
this is fixed in 1.14.1.

Please let me know if this solves the issue for you.

**Comment by deanfourie1** [comment]
Just test this, same errors as before.


```
Get latest information from git
Checkout to latest tag
Note: switching to 'v1.14.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 915abb1 dont fail when no user table is found
From https://github.com/antedebaas/DMARC-SMTPTLS-Reports
 * tag               v1.14.1    -> FETCH_HEAD
Already up to date.
Install composer dependencies
update.sh: line 11: composer: command not found
clear cache
update.sh: line 14: php: command not found
skipping migrations as there is no .env.local file yet.
Create one this by running setup

run upgrade script
done

install assets
update.sh: line 29: php: command not found
warmup cache
update.sh: line 32: php: command not found
```

```
root@apps:/home/DMARC-SMTPTLS-Reports# bash installservice.sh
Installing systemd service...
Reloading systemd daemon...
start dmarcmailcheck timer...
root@apps:/home/DMARC-SMTPTLS-Reports# 
```

```
root@apps:/home/DMARC-SMTPTLS-Reports# systemctl status dmarcmailcheck
x dmarcmailcheck.service - Check mail for new dmarc reports
     Loaded: loaded (/lib/systemd/system/dmarcmailcheck.service; static)
     Active: failed (Result: exit-code) since Mon 2024-06-10 20:48:15 NZST; 7s ago
   Duration: 1ms
TriggeredBy: * dmarcmailcheck.timer
    Process: 3356176 ExecStart=php /home/DMARC-SMTPTLS-Reports/bin/console app:getreportsfrommailbox (code=exited, status=203/EXEC)
   Main PID: 3356176 (code=exited, status=203/EXEC)
        CPU: 684us

Jun 10 20:48:15 apps (php)[3356176]: dmarcmailcheck.service: Failed at step EXEC spawning php: No such file or directory
Jun 10 20:48:15 apps systemd[1]: Started dmarcmailcheck.service - Check mail for new dmarc reports.
Jun 10 20:48:15 apps systemd[1]: dmarcmailcheck.service: Main process exited, code=exited, status=203/EXEC
Jun 10 20:48:15 apps systemd[1]: dmarcmailcheck.service: Failed with result 'exit-code'.
root@apps:/home/DMARC-SMTPTLS-Reports# 
```

**Comment by antedebaas** [comment]
It says what’s wrong in there. 
nor php or composer could be found

**Comment by WebCodePoet** [comment]
Just to be patient, as I started this thread, it was about the MySQL installation routine, which I easily fixed by hand, so in general the installation worked, and I am happy with the software as it is. I don't have a docker installation done, I run it directly on a subdomain. So, thank you @antedebaas for creating this software for us to make DMARC easier!
